from http import HTTPStatus
from aenum import Enum, extend_enum

def extend_http_status():
    for name, value in ArtifactsHTTPStatus.items():
        extend_enum(HTTPStatus, name, value, name)

ArtifactsHTTPStatus = {
    # ACCOUNT ERROR CODES,
    "TOKEN_INVALID": 452,
    "TOKEN_EXPIRED": 453,
    "TOKEN_MISSING": 454,
    "TOKEN_GENERATION_FAIL": 455,
    "USERNAME_ALREADY_USED": 456,
    "EMAIL_ALREADY_USED": 457,
    "SAME_PASSWORD": 458,
    "CURRENT_PASSWORD_INVALID": 459,

    # CHARACTER ERROR CODES,
    "CHARACTER_NOT_ENOUGH_HP": 483,
    "CHARACTER_MAXIMUM_UTILITES_EQUIPED": 484,
    "CHARACTER_ITEM_ALREADY_EQUIPED": 485,
    "CHARACTER_LOCKED": 486,
    "CHARACTER_NOT_THIS_TASK": 474,
    "CHARACTER_TOO_MANY_ITEMS_TASK": 475,
    "CHARACTER_NO_TASK": 487,
    "CHARACTER_TASK_NOT_COMPLETED": 488,
    "CHARACTER_ALREADY_TASK": 489,
    "CHARACTER_ALREADY_MAP": 490,
    "CHARACTER_SLOT_EQUIPMENT_ERROR": 491,
    "CHARACTER_GOLD_INSUFFICIENT": 492,
    "CHARACTER_NOT_SKILL_LEVEL_REQUIRED": 493,
    "CHARACTER_NAME_ALREADY_USED": 494,
    "MAX_CHARACTERS_REACHED": 495,
    "CHARACTER_NOT_LEVEL_REQUIRED": 496,
    "CHARACTER_INVENTORY_FULL": 497,
    "CHARACTER_NOT_FOUND": 498,
    "CHARACTER_IN_COOLDOWN": 499,

    # ITEM ERROR CODES,
    "ITEM_INSUFFICIENT_QUANTITY": 471,
    "ITEM_INVALID_EQUIPMENT": 472,
    "ITEM_RECYCLING_INVALID_ITEM": 473,
    "ITEM_INVALID_CONSUMABLE": 476,
    "MISSING_ITEM": 478,

    # GRAND EXCHANGE ERROR CODES,
    "GE_MAX_QUANTITY": 479,
    "GE_NOT_IN_STOCK": 480,
    "GE_NOT_THE_PRICE": 482,
    "GE_TRANSACTION_IN_PROGRESS": 436,
    "GE_NO_ORDERS": 431,
    "GE_MAX_ORDERS": 433,
    "GE_TOO_MANY_ITEMS": 434,
    "GE_SAME_ACCOUNT": 435,
    "GE_INVALID_ITEM": 437,
    "GE_NOT_YOUR_ORDER": 438,

    # BANK ERROR CODES,
    "BANK_INSUFFICIENT_GOLD": 460,
    "BANK_TRANSACTION_IN_PROGRESS": 461,
    "BANK_FULL": 462,

    # MAPS ERROR CODES,
    "MAP_NOT_FOUND": 597,
    "MAP_CONTENT_NOT_FOUND": 598,
}
