#!/usr/bin/env bash
# Liveness axiom gate (Phase 19a). Iterates every theorem listed in
# `Formal/LivenessAudit.lean` (covers `Formal/Liveness/**/*.lean`) and
# asserts axioms ⊆ allow-list below. Writes a per-theorem manifest to
# `formal/gate/liveness_axioms.manifest` for transparency.
#
# Allow-list = {propext, Classical.choice, Quot.sound} ∪ Mathlib_standard
#            ∪ approved Liveness namespace axioms (see catalog below).
#
# Approved Liveness axioms (each requires user signoff + openapi citation):
#   * LIV-001: Formal.Liveness.Measure.xpToNextLevel        | spec: /v3/server/details (xp_curve) | approved 2026-05-30
#   * LIV-001: Formal.Liveness.Measure.xpToNextLevel_pos    | spec: /v3/server/details (xp_curve) | approved 2026-05-30
#
# New entries here require the same Phase-19a discipline: docstring header
# `-- AXIOM-ID: <id> | spec: <section> | approved: <date>` in the source.
#
# Mathlib_standard at the current pin (Mathlib v4.30.0 — see
# `formal/lakefile.toml`): empirically, foundational Mathlib theorems
# spanning real analysis (`Real.log_mul`, `Real.exp_log`), measure theory
# (`MeasureTheory.Measure.add_apply`), and probability mass functions
# (`PMF.toMeasure`) all reduce to exactly the same three Lean kernel
# axioms `{propext, Classical.choice, Quot.sound}`. No additional axioms
# (no `Quot.lift` extensions, no decidability axioms, no choice variants)
# were observed. The union therefore equals the safety set at this pin.
#
# If a future Mathlib bump introduces additional axioms, re-run the probe
# (a temporary `Formal/Liveness/_AxiomProbe.lean` that `#print axioms` on
# the same foundational set) and expand the regex accordingly, citing the
# new pin in this comment.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."   # formal/
. "$HOME/.elan/env" 2>/dev/null || true

ALLOWED_RE='(propext|Classical\.choice|Quot\.sound|xpToNextLevel|xpToNextLevel_pos)'

OUT_RAW="$(lake env lean Formal/LivenessAudit.lean 2>&1)"
echo "$OUT_RAW"

# Fold wrapped lines (continuations starting with whitespace) into their
# `depends on axioms:` parent so the bracket is one token.
OUT="$(printf '%s\n' "$OUT_RAW" | python3 -c 'import sys, re; print(re.sub(r"\n\s+", " ", sys.stdin.read()))')"

if echo "$OUT" | grep -Eiq 'sorryAx|sorry'; then
  echo "GATE FAIL (liveness): sorry detected"; exit 1
fi

# Write the manifest (transparency artifact — committed).
MANIFEST="gate/liveness_axioms.manifest"
{
  echo "# Liveness axiom manifest — generated by check_axioms_liveness.sh"
  echo "# Mathlib pin: v4.30.0 (see lakefile.toml)"
  echo "# Allow-list: {propext, Classical.choice, Quot.sound,"
  echo "#              Formal.Liveness.Measure.xpToNextLevel(_pos) [LIV-001]}"
  echo "$OUT" | grep -E 'depends on axioms|does not depend on any axioms' || true
} > "$MANIFEST"
echo "wrote $MANIFEST"

# Every `depends on axioms: [...]` bracket must be a subset of the allow-list.
if echo "$OUT" | grep -E 'depends on axioms' \
   | grep -Evq "\\[${ALLOWED_RE}(, ${ALLOWED_RE})*\\]"; then
  echo "GATE FAIL (liveness): axiom outside allow-list"; exit 1
fi

# Cross-namespace leak check: no liveness-only axiom may appear in the
# safety pass output. At the current pin the allow-lists coincide, so any
# axiom appearing in the liveness manifest is by construction also safety-
# legal. If the allow-lists ever diverge, add an explicit cross-check here
# that diffs the safety Audit output against liveness-only axioms.
echo "liveness axiom check OK"
