[tool.poetry]
name = "artifactsmmo"
version = "0.0.1"
description = "Playing the Artifacts MMO"
authors = ["Brett Lentz <brett.lentz@gmail.com>"]
license = "GNU Affero General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
aenum = ">= 3.1.0"
artifactsmmo-api-client = { path = "./artifactsmmo-api-client" }
openapi-python-client = ">=0.24.0"
python = ">=3.10,<4"
pyyaml = ">=6.0"

[tool.poetry.group.test.dependencies]
pytest = ">= 8.4.0"
pytest-cov = "^6.2.1"


[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
