# GOAP Actions Configuration - Consolidated State Version
# Uses the new consolidated state system with richer data types

actions:
  # Combat search bridge action
  initiate_combat_search:
    conditions:
      combat_context:
        status: 'idle'
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      combat_context:
        status: 'searching'
      resource_availability:
        monsters: false
    weight: 2
    
  # Find monsters action
  find_monsters:
    conditions:
      combat_context:
        status: 'searching'
      character_status:
        alive: true
    reactions:
      resource_availability:
        monsters: true
      combat_context:
        status: 'ready'
      location_context:
        at_target: true
    weight: 2
    
  # Movement actions
  move:
    conditions:
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_target: true
    weight: 1
    
  # Combat actions
  attack:
    conditions:
      combat_context:
        status: "ready"
      character_status:
        safe: true
        alive: true
    reactions:
      combat_context:
        status: "completed"
    weight: 3
    
  # Rest actions
  rest:
    conditions:
      character_status:
        hp_percentage: '<100'
    reactions:
      character_status:
        hp_percentage: 100
    weight: 1
    
  wait:
    conditions:
      character_status:
        cooldown_active: true
    reactions:
      character_status:
        cooldown_active: false
    weight: 1
    
  # Equipment analysis and planning
  analyze_equipment_gaps:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'  # Will be overridden to 'combat_ready' if equipment is adequate
        gaps_analyzed: true
    weight: 1
    
  select_optimal_slot:
    conditions:
      equipment_status:
        gaps_analyzed: true
        target_slot: null
    reactions:
      equipment_status:
        target_slot: 'weapon'
    weight: 1
    
  evaluate_recipes:
    conditions:
      equipment_status:
        target_slot: '!null'
        selected_item: null
    reactions:
      equipment_status:
        selected_item: 'wooden_staff'
        recipe_evaluated: true
    weight: 2
    
  # Workshop discovery
  find_workshops:
    conditions:
      workshop_status:
        discovered: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      workshop_status:
        discovered: true
      location_context:
        workshop_known: true
    weight: 2
    
  # Move to workshop
  move_to_workshop:
    conditions:
      workshop_status:
        discovered: true
      location_context:
        at_workshop: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_workshop: true
    weight: 1
    
  # Crafting actions
  check_skill_requirement:
    conditions:
      equipment_status:
        selected_item: '!null'
      skill_status:
        checked: false
    reactions:
      skill_status:
        checked: true
        sufficient: true
    weight: 1
    
  craft_item:
    conditions:
      location_context:
        at_workshop: true
      materials:
        status: 'sufficient'
      skill_status:
        sufficient: true
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      equipment_status:
        item_crafted: true
      inventory:
        updated: true
    weight: 3
    
  # Equip actions
  equip_item:
    conditions:
      equipment_status:
        item_crafted: true
        equipped: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      equipment_status:
        equipped: true
        upgrade_status: 'completed'
    weight: 2
    
  # Resource gathering
  find_resources:
    conditions:
      materials:
        status: 'needed'
      resource_availability:
        resources: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        resources: true
      location_context:
        at_resource: true
    weight: 2
    
  gather_resources:
    conditions:
      location_context:
        at_resource: true
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      materials:
        gathered: true
      inventory:
        updated: true
    weight: 2
    
  # Combat Flow Bridge Actions
  reset_combat_context:
    conditions:
      combat_context:
        status: 'completed'
    reactions:
      combat_context:
        status: 'idle'
        target: null
        location: null
    weight: 1
    
  abort_combat_search:
    conditions:
      combat_context:
        status: 'searching'
      resource_availability:
        monsters: false
    reactions:
      combat_context:
        status: 'idle'
        target: null
        location: null
    weight: 1.5
    
  mark_combat_not_viable:
    conditions:
      combat_context:
        recent_win_rate: '<0.2'
      character_status:
        alive: true
    reactions:
      combat_context:
        status: 'not_viable'
    weight: 2
    
  recover_combat_viability:
    conditions:
      combat_context:
        status: 'not_viable'
      equipment_status:
        upgrade_status: 'completed'
    reactions:
      combat_context:
        status: 'idle'
        recent_win_rate: 1.0
    weight: 2.5
    
  # Equipment Flow Bridge Actions
  initiate_equipment_analysis:
    conditions:
      equipment_status:
        upgrade_status: 'needs_analysis'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
    weight: 1.5
    
  mark_equipment_crafting:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
        selected_item: '!null'
    reactions:
      equipment_status:
        upgrade_status: 'crafting'
    weight: 1.5
    
  mark_equipment_ready:
    conditions:
      equipment_status:
        upgrade_status: 'crafting'
        item_crafted: true
    reactions:
      equipment_status:
        upgrade_status: 'ready'
    weight: 1.5
    
  complete_equipment_upgrade:
    conditions:
      equipment_status:
        upgrade_status: 'ready'
        equipped: true
    reactions:
      equipment_status:
        upgrade_status: 'completed'
    weight: 2
    
  reset_equipment_upgrade:
    conditions:
      equipment_status:
        upgrade_status: 'completed'
    reactions:
      equipment_status:
        upgrade_status: 'needs_analysis'
        selected_item: null
        target_slot: null
    weight: 1