# AI Player Configuration
#
# This file configures AI behavior, goal priorities, and planning parameters
# for the ArtifactsMMO AI Player system. All settings use Pydantic Settings
# for type-safe configuration loading and validation.

goals:
  priority_levels:
    survival: 10      # HP management, rest actions
    progression: 8    # XP and level advancement
    economic: 6       # Gold accumulation and trading
    exploration: 4    # Map discovery and movement
    collection: 2     # Item gathering and inventory management

planning:
  max_plan_depth: 10
  replan_interval: 300  # seconds between replanning
  emergency_replan_triggers:
    - low_hp           # HP below safety threshold
    - unexpected_location  # Character not where expected
    - api_error        # API call failures
    - cooldown_exceeded    # Cooldown longer than expected

actions:
  movement:
    pathfinding_algorithm: "a_star"
    avoid_monsters: true
    max_movement_distance: 50
  
  combat:
    min_hp_percentage: 0.3
    preferred_combat_level_range: [-2, 1]  # Relative to character level
    retreat_hp_threshold: 0.2
  
  gathering:
    resource_priority:
      - "copper_ore"
      - "ash_wood"
      - "gudgeon"
    skill_level_buffer: 0  # Gather resources at exact skill level
  
  crafting:
    auto_craft_equipment: true
    prioritize_weapon_upgrades: true
    max_crafting_queue: 5

thresholds:
  low_hp_percentage: 0.3
  inventory_full_threshold: 0.9
  gold_reserve_minimum: 100
  emergency_rest_hp: 0.1

logging:
  action_execution: "INFO"
  goap_planning: "DEBUG"
  state_management: "INFO"
  api_calls: "WARNING"