# Architecture-Compliant GOAP Actions Configuration
# This file defines core actions using valid StateParameters and subgoal request patterns
# Bridge actions have been removed in favor of subgoal requests per docs/ARCHITECTURE.md

# State defaults - SINGLE SOURCE OF TRUTH for state parameters that CANNOT be obtained from knowledge-base + API queries
# Following heuristic: "can this information be obtained by querying the (knowledge-base + unified_context)? If yes, don't create a new parameter."
state_defaults:
  # Character health status - computed from API HP data but cached for GOAP planning
  character_status.healthy: true
  character_status.cooldown_active: false
  
  # Target context - tracks current target items for actions (not in API)
  target.item: null
  target.slot: null
  target.recipe: null
  
  # Combat context - tracks current combat state (not available from API)
  combat_context.status: "idle"
  
  # Materials workflow status - tracks gathering/crafting progression (not in API)
  materials.status: "unknown"
  materials.gathered: false
  
  # Equipment workflow status - tracks crafting/equipping progression (not in API)
  equipment_status.item_crafted: false
  equipment_status.equipped: false
  
  # Resource discovery cache - tracks what monsters/resources are available (not in API)
  resource_availability.monsters: false
  
  # Skill requirements evaluation - tracks if character skills are sufficient for current task
  skill_requirements.sufficient: false
  
  # Location context - tracks movement completion
  location_context.at_target: false

actions:
  # Core movement action - success determined by knowledge-base lookup
  move:
    conditions:
      character_status.healthy: true
      character_status.cooldown_active: false
    reactions:
      location_context.at_target: true
    weight: 1.0
    description: Move character to coordinates specified in ActionContext
    metadata:
      type: "execution"
      failure_recovery: "coordinate_search"
    
  # Core action to find monsters for combat
  find_monsters:
    conditions:
      character_status.healthy: true
      combat_context.status: idle
    reactions:
      resource_availability.monsters: true
      combat_context.status: ready
    weight: 2.0
    description: Find monsters suitable for combat using knowledge-base lookup
    metadata:
      type: "discovery"
      triggers_replan: true
    
  # Core combat action - attack when monsters are available
  attack:
    conditions:
      character_status.healthy: true
      resource_availability.monsters: true
      combat_context.status: ready
    reactions:
      combat_context.status: completed
    weight: 3.0
    description: Attack available monster
    metadata:
      type: "execution"
  
  reset_combat_context:
    conditions:
      combat_context.status: [completed, defeated]
    reactions:
      combat_context.status: idle
      resource_availability.monsters: false
    weight: 1.0
    description: Reset combat context from completed or defeated to idle
    metadata:
      type: "execution"
    
  # Core resource gathering - requests movement subgoals if needed  
  gather_resources:
    conditions:
      character_status.healthy: true
      materials.status: insufficient
    reactions:
      materials.status: gathered
      materials.gathered: true
    weight: 2.0
    description: Gather required resources, requesting movement subgoals if needed
    metadata:
      type: "execution"
    
  # Core crafting action - requests material gathering and movement subgoals
  craft_item:
    conditions:
      character_status.healthy: true
      materials.status: sufficient
      skill_requirements.sufficient: true
    reactions:
      equipment_status.item_crafted: true
    weight: 3.0
    description: Craft item, requesting subgoals for materials and workshop movement
    metadata:
      type: "execution"
    
  # Core equipment action - requests crafting subgoals if needed
  equip_item:
    conditions:
      character_status.healthy: true
      equipment_status.item_crafted: true
    reactions:
      equipment_status.equipped: true
    weight: 2.0
    description: Equip crafted item
    metadata:
      type: "execution"
    
  # Simple utility actions using valid StateParameters
  rest:
    conditions:
      character_status.healthy: false
    reactions:
      character_status.healthy: true
    weight: 1.5
    description: Rest to recover HP when needed
    metadata:
      type: "execution"
    
  wait:
    conditions:
      character_status.cooldown_active: true
    reactions:
      character_status.cooldown_active: false
    weight: 0.1
    description: Wait for cooldown to expire before taking other actions
    metadata:
      type: "execution"
  
  # Discovery actions that trigger replanning when they provide new knowledge
  find_resources:
    conditions:
      character_status.healthy: true
    reactions:
      resource_availability.resources: true
    weight: 2.0
    description: Find resources suitable for gathering using knowledge-base lookup
    metadata:
      type: "discovery"
      triggers_replan: true
      
  find_workshops:
    conditions:
      character_status.healthy: true
    reactions:
      resource_availability.workshops: true
    weight: 2.0
    description: Find workshops suitable for crafting using knowledge-base lookup
    metadata:
      type: "discovery"
      triggers_replan: true
      
  find_correct_workshop:
    conditions:
      character_status.healthy: true
    reactions:
      resource_availability.correct_workshop: true
    weight: 2.0
    description: Find correct workshop for specific crafting task
    metadata:
      type: "discovery"
      triggers_replan: true
      
  evaluate_weapon_recipes:
    conditions:
      character_status.healthy: true
    reactions:
      equipment_status.recipe_evaluated: true
    weight: 2.0
    description: Evaluate weapon recipes to determine best crafting options
    metadata:
      type: "discovery"
      triggers_replan: true
      
  lookup_item_info:
    conditions:
      character_status.healthy: true
    reactions:
      target.item_info_known: true
    weight: 2.0
    description: Look up item information from knowledge base or API
    metadata:
      type: "discovery"
      triggers_replan: true
      
  explore_map:
    conditions:
      character_status.healthy: true
    reactions:
      map.explored: true
    weight: 2.0
    description: Explore map to discover new locations and resources
    metadata:
      type: "discovery"
      triggers_replan: true

metadata:
  version: '3.0'
  description: Architecture-compliant action set using subgoal request patterns
  created_by: Claude Code Architecture Refactor
  last_updated: '2025-07-12'