# Default GOAP Actions Configuration - Consolidated State Version
# This file defines the default set of actions available to the AI player's Goal-Oriented Action Planning system

actions:
  # Movement actions
  move:
    conditions:
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_target: true
    weight: 1.0
    description: "Move character to a target location"
    
  # Combat actions - simplified flow
  initiate_combat_search:
    conditions:
      combat_context:
        status: 'idle'
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      combat_context:
        status: 'searching'
    weight: 2.0
    description: "Initiate transition from idle to searching for monsters"
    
  find_monsters:
    conditions:
      combat_context:
        status: 'searching'
      resource_availability:
        monsters: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        monsters: true
      combat_context:
        status: 'ready'
    weight: 2.0
    description: "Find nearby monsters suitable for combat (legacy - use search_monsters)"
    parameters:
      minimum_win_rate: 0.0
    
  attack:
    conditions:
      combat_context:
        status: 'ready'
      resource_availability:
        monsters: true
      character_status:
        safe: true
        alive: true
    reactions:
      combat_context:
        status: 'completed'
      goal_progress:
        monsters_hunted: '+1'
        has_gained_xp: true
    weight: 3.0
    description: "Attack a monster in combat"
    
  # Recovery actions
  rest:
    conditions:
      character_status:
        alive: true
    reactions:
      character_status:
        safe: true
    weight: 1.5
    description: "Rest to recover HP when needed"
    
  wait:
    conditions:
      character_status:
        cooldown_active: true
    reactions:
      character_status:
        cooldown_active: false
    weight: 0.1
    description: "Wait for cooldown to expire before taking other actions"
    
  # Healing actions
  initiate_healing:
    conditions:
      character_status:
        alive: true
        safe: false
      healing_context:
        healing_status: 'idle'
    reactions:
      healing_context:
        healing_status: 'in_progress'
    weight: 1.0
    description: "Initiate healing process when character is unsafe"
    
  complete_healing:
    conditions:
      healing_context:
        healing_status: 'in_progress'
      character_status:
        safe: true
    reactions:
      healing_context:
        healing_status: 'complete'
    weight: 1.0
    description: "Complete healing process after character is safe"
    
  # Equipment upgrade actions
  initiate_equipment_analysis:
    conditions:
      equipment_status:
        upgrade_status: 'needs_analysis'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
    weight: 1.5
    description: "Initiate equipment analysis to prepare for upgrades"
    
  analyze_equipment_gaps:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
        gaps_analyzed: true
    weight: 1.0
    description: "Analyze gaps in character equipment to identify upgrade needs"
    
  select_optimal_slot:
    conditions:
      equipment_status:
        gaps_analyzed: true
        has_target_slot: false
      character_status:
        alive: true
    reactions:
      equipment_status:
        has_target_slot: true
    weight: 1.5
    description: "Select the optimal equipment slot for crafting based on gaps and skill"
    
  select_recipe:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
        has_target_slot: true
    reactions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
    weight: 2.0
    description: "Select optimal recipe for equipment crafting"
    
  determine_material_requirements:
    conditions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
    weight: 1.0
    description: "Determine what materials are needed for the selected recipe"
    
  check_material_availability:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        status: 'sufficient'
    weight: 1.0
    description: "Check if required materials are available in inventory and mark as sufficient"
    
  determine_material_insufficiency:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        status: 'insufficient'
    weight: 1.0
    description: "Determine that required materials are insufficient and need gathering"
    
  # Material gathering chain
  find_resources:
    conditions:
      materials:
        status: 'insufficient'
        availability_checked: true
        quantities_calculated: true
      resource_availability:
        resources: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        resources: true
      location_context:
        resource_known: true
    weight: 2.0
    description: "Find locations of required resources"
    
  move_to_resource:
    conditions:
      location_context:
        resource_known: true
        at_resource: false
      materials:
        status: 'insufficient'
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_resource: true
    weight: 1.5
    description: "Move to resource location"
    
  gather_resources:
    conditions:
      location_context:
        at_resource: true
      materials:
        status: 'insufficient'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'gathered_raw'
        gathered: true
    weight: 2.0
    description: "Gather raw materials from resource location"
    
  gather_resource_quantity:
    conditions:
      location_context:
        at_resource: true
      materials:
        status: 'insufficient'
        quantities_calculated: true
        raw_materials_needed: true
      character_status:
        alive: true
    reactions:
      materials:
        status: 'gathered_raw'
        gathered: true
      inventory:
        updated: true
    weight: 2.5
    description: "Gather specific quantity of resources to meet crafting needs"
    
  # Material transformation chain
  find_workshops:
    conditions:
      materials:
        status: 'gathered_raw'
      location_context:
        workshop_known: false
      character_status:
        alive: true
    reactions:
      location_context:
        workshop_known: true
      workshop_status:
        discovered: true
    weight: 1.5
    description: "Find the appropriate workshop for material transformation"
    
  move_to_workshop:
    conditions:
      location_context:
        workshop_known: true
        at_workshop: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_workshop: true
    weight: 1.0
    description: "Move to workshop location"
    
  transform_materials:
    conditions:
      location_context:
        at_workshop: true
      materials:
        status: 'gathered_raw'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'transformed'
        transformation_complete: true
    weight: 2.0
    description: "Transform raw materials (e.g., ore to bars) at workshop"
    
  verify_material_sufficiency:
    conditions:
      materials:
        transformation_complete: true
        status: 'transformed'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'sufficient'
        ready_to_craft: true
    weight: 1.0
    description: "Verify all materials are now sufficient after transformation"
    
  verify_skill_requirements:
    conditions:
      equipment_status:
        has_selected_item: true
      materials:
        status: 'sufficient'
      character_status:
        alive: true
    reactions:
      skill_requirements:
        verified: true
        sufficient: true
    weight: 1.0
    description: "Verify character has sufficient skill level for crafting"
    
  craft_item:
    conditions:
      skill_requirements:
        verified: true
        sufficient: true
      materials:
        status: 'sufficient'
      location_context:
        at_workshop: true
      equipment_status:
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      equipment_status:
        item_crafted: true
      inventory:
        updated: true
    weight: 3.0
    description: "Craft the selected item at the workshop"
    
  check_inventory:
    conditions:
      equipment_status:
        item_crafted: true
      character_status:
        alive: true
    reactions:
      inventory:
        checked: true
      equipment_status:
        ready_to_equip: true
    weight: 1.0
    description: "Check inventory for crafted items and resources"
    
  equip_item:
    conditions:
      equipment_status:
        item_crafted: true
        ready_to_equip: true
        has_selected_item: true
      inventory:
        checked: true
      character_status:
        alive: true
    reactions:
      equipment_status:
        equipped: true
        upgrade_status: 'completed'
    weight: 2.0
    description: "Equip the crafted item"
    
  complete_equipment_upgrade:
    conditions:
      equipment_status:
        equipped: true
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'completed'
    weight: 1.0
    description: "Complete equipment upgrade process after equipping"
    
  # Universal search actions - consolidates find_monsters, find_resources, find_workshops
  search_monsters:
    conditions:
      combat_context:
        status: 'searching'
      resource_availability:
        monsters: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        monsters: true
      combat_context:
        status: 'ready'
    weight: 2.0
    description: "Universal search for monsters suitable for combat"
    parameters:
      search_content_type: "monster"
      minimum_win_rate: 0.0
      
  search_resources:
    conditions:
      materials:
        status: 'insufficient'
        availability_checked: true
        quantities_calculated: true
      resource_availability:
        resources: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        resources: true
      location_context:
        resource_known: true
    weight: 2.0
    description: "Universal search for resource locations"
    parameters:
      search_content_type: "resource"
      
  search_workshops:
    conditions:
      materials:
        status: 'gathered_raw'
      location_context:
        workshop_known: false
      character_status:
        alive: true
    reactions:
      location_context:
        workshop_known: true
      workshop_status:
        discovered: true
    weight: 1.5
    description: "Universal search for workshops"
    parameters:
      search_content_type: "workshop"
      
  # Universal movement actions - consolidates move, move_to_resource, move_to_workshop
  move_coordinates:
    conditions:
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_target: true
    weight: 1.0
    description: "Universal movement to specific coordinates"
    parameters:
      movement_type: "coordinate"
      
  move_to_target_resource:
    conditions:
      location_context:
        resource_known: true
        at_resource: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_resource: true
    weight: 1.5
    description: "Universal movement to target resource location"
    parameters:
      movement_type: "resource"
      target_resource_key: "target_resource"
      
  move_to_target_workshop:
    conditions:
      location_context:
        workshop_known: true
        at_workshop: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_workshop: true
    weight: 1.0
    description: "Universal movement to target workshop location"
    parameters:
      movement_type: "workshop"
      target_workshop_key: "target_workshop"
      
  # Universal material actions - consolidates material workflow actions  
  determine_requirements:
    conditions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
    weight: 1.0
    description: "Universal action to determine material requirements"
    parameters:
      material_workflow: "determine_requirements"
      
  check_availability:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        status: 'sufficient'
    weight: 1.0
    description: "Universal action to check material availability"
    parameters:
      material_workflow: "check_availability"
      
  determine_insufficiency:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        status: 'insufficient'
    weight: 1.0
    description: "Universal action to determine material insufficiency"
    parameters:
      material_workflow: "determine_insufficiency"
      
  calculate_quantities:
    conditions:
      materials:
        requirements_determined: true
        status: 'insufficient'
        availability_checked: true
      equipment_status:
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      materials:
        quantities_calculated: true
        raw_materials_needed: true
    weight: 1.0
    description: "Universal action to calculate material quantities"
    parameters:
      material_workflow: "calculate_quantities"
      
  gather_materials:
    conditions:
      materials:
        status: 'insufficient'
        availability_checked: true
        quantities_calculated: true
        raw_materials_needed: true
      character_status:
        alive: true
    reactions:
      materials:
        status: 'gathered_raw'
        gathered: true
      inventory:
        updated: true
    weight: 2.5
    description: "Universal action to gather missing materials"
    parameters:
      material_workflow: "gather_materials"
      
  check_gathering:
    conditions:
      materials:
        status: 'gathered_raw'
        gathered: true
      character_status:
        alive: true
    reactions:
      materials:
        status: 'sufficient'
        ready_to_craft: true
    weight: 1.0
    description: "Universal action to check if gathering is complete"
    parameters:
      material_workflow: "check_gathering_complete"

# Default configuration metadata
metadata:
  version: "2.0"
  description: "Default action set for GOAP-based AI player using consolidated state system"
  created_by: "Claude Code"
  last_updated: "2025-07-01"