# Default GOAP Actions Configuration - Consolidated State Version
# This file defines the default set of actions available to the AI player's Goal-Oriented Action Planning system

actions:
  # Movement actions
  move:
    conditions:
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_target: true
    weight: 1.0
    description: "Move character to a target location"
    
  # Combat actions
  initiate_combat_search:
    conditions:
      combat_context:
        status: 'idle'
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      combat_context:
        status: 'searching'
    weight: 2.0
    description: "Begin searching for monsters"
    
  find_monsters:
    conditions:
      combat_context:
        status: 'searching'
      resource_availability:
        monsters: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        monsters: true
      combat_context:
        status: 'ready'
      location_context:
        at_target: true
    weight: 2.0
    description: "Find nearby monsters suitable for combat"
    
  attack:
    conditions:
      combat_context:
        status: 'ready'
      character_status:
        safe: true
        alive: true
    reactions:
      combat_context:
        status: 'completed'
      goal_progress:
        monsters_hunted: '+1'
    weight: 3.0
    description: "Attack a monster in combat"
    
  # Recovery actions
  rest:
    conditions:
      character_status:
        hp_percentage: '<100'
        alive: true
    reactions:
      character_status:
        hp_percentage: 100
        safe: true
    weight: 1.5
    description: "Rest to recover HP when needed"
    
  wait:
    conditions:
      character_status:
        cooldown_active: true
    reactions:
      character_status:
        cooldown_active: false
    weight: 0.1
    description: "Wait for cooldown to expire before taking other actions"
    
  # Equipment upgrade actions
  initiate_equipment_analysis:
    conditions:
      equipment_status:
        upgrade_status: 'needs_analysis'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
    weight: 1.5
    description: "Initiate equipment analysis to prepare for upgrades"
    
  analyze_equipment_gaps:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
        gaps_analyzed: true
    weight: 1.0
    description: "Analyze gaps in character equipment to identify upgrade needs"
    
  select_optimal_slot:
    conditions:
      equipment_status:
        gaps_analyzed: true
        has_target_slot: false
      character_status:
        alive: true
    reactions:
      equipment_status:
        has_target_slot: true
    weight: 1.5
    description: "Select the optimal equipment slot for crafting based on gaps and skill"
    
  select_recipe:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
        has_target_slot: true
    reactions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
    weight: 2.0
    description: "Select optimal recipe for equipment crafting"
    
  determine_material_requirements:
    conditions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
    weight: 1.0
    description: "Determine what materials are needed for the selected recipe"
    
  check_material_availability:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        status: 'sufficient'
    weight: 1.0
    description: "Check if required materials are available in inventory"
    
  verify_skill_requirements:
    conditions:
      equipment_status:
        has_selected_item: true
      materials:
        status: 'sufficient'
      character_status:
        alive: true
    reactions:
      skill_requirements:
        verified: true
        sufficient: true
    weight: 1.0
    description: "Verify character has sufficient skill level for crafting"
    
  complete_equipment_upgrade:
    conditions:
      skill_requirements:
        verified: true
        sufficient: true
      materials:
        status: 'sufficient'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'completed'
    weight: 3.0
    description: "Complete equipment upgrade process"

# Default configuration metadata
metadata:
  version: "2.0"
  description: "Default action set for GOAP-based AI player using consolidated state system"
  created_by: "Claude Code"
  last_updated: "2025-07-01"