# Equipment Upgrade Actions Configuration
# Enhanced GOAP actions for proper material gathering chains

actions:
  # Core equipment upgrade flow
  initiate_equipment_analysis:
    conditions:
      equipment_status:
        upgrade_status: 'needs_analysis'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
    weight: 1.5
    description: "Initiate equipment analysis to prepare for upgrades"
    
  analyze_equipment_gaps:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'analyzing'
        gaps_analyzed: true
    weight: 1.0
    description: "Analyze gaps in character equipment to identify upgrade needs"
    
  select_optimal_slot:
    conditions:
      equipment_status:
        gaps_analyzed: true
        has_target_slot: false
      character_status:
        alive: true
    reactions:
      equipment_status:
        has_target_slot: true
    weight: 1.5
    description: "Select the optimal equipment slot for crafting based on gaps and skill"
    
  select_recipe:
    conditions:
      equipment_status:
        upgrade_status: 'analyzing'
        has_target_slot: true
    reactions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
    weight: 2.0
    description: "Select optimal recipe for equipment crafting"
    
  determine_material_requirements:
    conditions:
      equipment_status:
        upgrade_status: 'ready'
        has_selected_item: true
      character_status:
        alive: true
    reactions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
    weight: 1.0
    description: "Determine what materials are needed for the selected recipe"
    
  check_material_availability:
    conditions:
      materials:
        requirements_determined: true
        status: 'checking'
      inventory:
        updated: true
      character_status:
        alive: true
    reactions:
      materials:
        availability_checked: true
        # Don't set status - let runtime determine
    weight: 1.0
    description: "Check if required materials are available in inventory"
    
  # Material gathering chain actions
  find_resources:
    conditions:
      materials:
        status: 'insufficient'
        availability_checked: true
      resource_availability:
        resources: false
      character_status:
        alive: true
    reactions:
      resource_availability:
        resources: true
      location_context:
        resource_known: true
    weight: 2.0
    description: "Find locations of required resources"
    
  move_to_resource:
    conditions:
      location_context:
        resource_known: true
        at_resource: false
      materials:
        status: 'insufficient'
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_resource: true
    weight: 1.5
    description: "Move to resource location"
    
  gather_resources:
    conditions:
      location_context:
        at_resource: true
      materials:
        status: 'insufficient'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'gathered_raw'
        gathered: true
    weight: 2.0
    description: "Gather raw materials from resource location"
    
  # Material transformation chain
  find_workshop:
    conditions:
      materials:
        status: 'gathered_raw'
      location_context:
        workshop_known: false
      character_status:
        alive: true
    reactions:
      location_context:
        workshop_known: true
      workshop_status:
        discovered: true
    weight: 1.5
    description: "Find the appropriate workshop for material transformation"
    
  move_to_workshop:
    conditions:
      location_context:
        workshop_known: true
        at_workshop: false
      character_status:
        alive: true
        cooldown_active: false
    reactions:
      location_context:
        at_workshop: true
    weight: 1.0
    description: "Move to workshop location"
    
  transform_materials:
    conditions:
      location_context:
        at_workshop: true
      materials:
        status: 'gathered_raw'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'transformed'
        transformation_complete: true
    weight: 2.0
    description: "Transform raw materials (e.g., ore to bars) at workshop"
    
  # Re-check after transformation
  verify_material_sufficiency:
    conditions:
      materials:
        transformation_complete: true
        status: 'transformed'
      character_status:
        alive: true
    reactions:
      materials:
        status: 'sufficient'
        ready_to_craft: true
    weight: 1.0
    description: "Verify all materials are now sufficient after transformation"
    
  # Skill and crafting completion
  verify_skill_requirements:
    conditions:
      equipment_status:
        has_selected_item: true
      materials:
        status: 'sufficient'
      character_status:
        alive: true
    reactions:
      skill_requirements:
        verified: true
        sufficient: true
    weight: 1.0
    description: "Verify character has sufficient skill level for crafting"
    
  complete_equipment_upgrade:
    conditions:
      skill_requirements:
        verified: true
        sufficient: true
      materials:
        status: 'sufficient'
      location_context:
        at_workshop: true
      character_status:
        alive: true
    reactions:
      equipment_status:
        upgrade_status: 'completed'
    weight: 3.0
    description: "Complete equipment upgrade process by crafting the item"

# Metadata
metadata:
  version: "1.0"
  description: "Enhanced equipment upgrade actions with full material gathering chain"
  created_by: "Claude Code"
  notes: |
    This configuration provides a complete chain for equipment upgrades:
    1. Analyze equipment and select recipe
    2. Check material availability
    3. If insufficient: find resources → move → gather
    4. Transform materials if needed (ore → bars)
    5. Move to workshop if not already there
    6. Craft the equipment