# GOAP Goal Templates Configuration - Consolidated State Version
# Uses the new consolidated state system with richer data types

goal_templates:
  # Core character progression goals
  level_up:
    description: "Advance character to next level through combat and experience gain"
    objective_type: "progression"
    target_state:
      character_status:
        level: "${current_level + 1}"
        safe: true
        alive: true
      goal_progress:
        monsters_hunted: ">0"
    strategy:
      max_iterations: 20
      hunt_radius: 4
      xp_target: 150
      safety_priority: true
      rest_threshold: 30  # HP percentage
      attack_threshold: 15  # HP percentage
    success_conditions:
      - type: "character_level"
        operator: ">="
        value: "${target_level}"
      - type: "character_alive"
        operator: "=="
        value: true
        
  hunt_monsters:
    description: "Hunt monsters for experience and loot"
    objective_type: "combat"
    target_state:
      combat_context:
        status: "completed"
      character_status:
        safe: true
    strategy:
      search_radius: 4
      max_search_attempts: 5
      level_range: 2
      prioritize_known_monsters: true
      
  bootstrap_character:
    description: "Get low-level character to viable state through equipment progression"
    objective_type: "equipment_progression"
    target_state:
      character_status:
        level: 3
        safe: true
      equipment_status:
        weapon: "!null"
        upgrade_status: "completed"
    strategy:
      max_iterations: 30
      equipment_priority: ["weapon", "shield"]
      focus_combat_effectiveness: true
      multi_step_thinking: true
      
  upgrade_weapon:
    description: "Craft and equip a better weapon for improved combat effectiveness"
    objective_type: "equipment_progression"
    target_state:
      equipment_status:
        weapon: "!null"
        upgrade_status: "completed"
      character_status:
        safe: true
    strategy:
      equipment_type: "weapon"
      level_improvement_threshold: 1
      search_radius: 4
      max_craft_attempts: 5
      
# Goal selection rules - determines which goals to pursue based on current state
goal_selection_rules:
  # Emergency priorities (highest priority)
  emergency:
    - condition:
        character_status:
          alive: false
      goal: "revive_character"
      priority: 100
      
    - condition:
        character_status:
          hp_percentage: "<30"
          alive: true
      goal: "get_to_safety"
      priority: 99
      
    - condition:
        combat_context:
          status: "not_viable"
        character_status:
          level: "<=5"
          safe: true
      goal: "bootstrap_character"
      priority: 96
      
  # Maintenance priorities
  maintenance:
    - condition:
        character_status:
          cooldown_active: true
      goal: "wait_for_cooldown"
      priority: 80
      
  # Progression priorities
  progression:
    - condition:
        character_status:
          safe: true
          hp_percentage: ">=80"
        combat_context:
          status: "idle"
      goal: "hunt_monsters"
      priority: 60

# State calculation rules
state_calculation_rules:
  # Character status computations
  character_status.safe:
    formula: "character_status.hp_percentage >= 30"
    
  character_status.cooldown_active:
    type: "computed"
    method: "check_cooldown_expiration"
    
  # Combat context computations
  combat_context.status:
    type: "computed"
    method: "compute_combat_context_status"
    
  combat_context.recent_win_rate:
    type: "computed"
    method: "compute_recent_win_rate"
    
# Configuration thresholds
thresholds:
  # Health and safety thresholds (percentages)
  safe_hp_percentage: 30
  rest_hp_percentage: 30
  attack_hp_percentage: 15
  
  # Combat viability thresholds
  min_combat_win_rate: 0.2
  recency_decay_factor: 0.9
  
  # Search and exploration parameters
  default_search_radius: 2
  max_search_radius: 4
  level_matching_range: 2