# GOAP Goal Templates Configuration - Refactored Version
# Uses simple, declarative target states with basic comparable types only
# Complex logic moved to 4-step execution flow and GOAP planning

goal_templates:
  # Core character progression goals
  level_up:
    description: "Advance character to next level through combat and experience gain"
    objective_type: "progression"
    parameters:
      target_level: null  # Set at runtime by mission executor
    target_state:
      character_status:
        alive: true
        safe: true
      goal_progress:
        has_gained_xp: true
    strategy:
      max_iterations: 20
      hunt_radius: 4
      safety_priority: true
      rest_threshold: 30
      attack_threshold: 15
        
  hunt_monsters:
    description: "Hunt monsters for experience and loot"
    objective_type: "combat"
    target_state:
      goal_progress:
        has_gained_xp: true
    strategy:
      search_radius: 4
      max_search_attempts: 5
      level_range: 2
      prioritize_known_monsters: true
      
  upgrade_weapon:
    description: "Craft and equip a better weapon for improved combat effectiveness"
    objective_type: "equipment_progression"
    target_state:
      equipment_status:
        upgrade_status: "completed"
    strategy:
      equipment_type: "weapon"
      level_improvement_threshold: 1
      search_radius: 4
      max_craft_attempts: 5
      
  get_to_safety:
    description: "Rest to restore HP when in danger"
    objective_type: "maintenance"
    target_state:
      healing_context:
        healing_status: "complete"
      character_status:
        safe: true
    strategy:
      max_iterations: 5
      
  wait_for_cooldown:
    description: "Wait for character cooldown to expire"
    objective_type: "maintenance"
    target_state:
      character_status:
        cooldown_active: false
    strategy:
      max_wait_time: 65
      
  revive_character:
    description: "Revive character if dead"
    objective_type: "emergency"
    target_state:
      character_status:
        alive: true
      healing_context:
        healing_status: "complete"
    strategy:
      max_attempts: 3
      
  gather_materials:
    description: "Gather required materials for crafting"
    objective_type: "resource_gathering"
    parameters:
      missing_materials: null  # Dict of materials to gather with quantities
      target_item: null        # Item being crafted
    target_state:
      materials:
        status: "sufficient"
        gathered: true
    strategy:
      search_radius: 4
      max_gathering_attempts: 10
      
  gather_resource:
    description: "Gather a specific resource in required quantity"
    objective_type: "resource_collection"
    target_state:
      materials:
        status: "sufficient"
        gathered: true
    strategy:
      search_radius: 4
      max_collection_attempts: 15
      
  move_to_location:
    description: "Move character to target coordinates"
    objective_type: "movement"
    parameters:
      target_x: null  # Target X coordinate
      target_y: null  # Target Y coordinate
    target_state:
      location_context:
        at_target: true
    strategy:
      max_move_attempts: 3
      
# Goal selection rules - uses simple boolean conditions
goal_selection_rules:
  # Emergency priorities (highest priority)
  emergency:
    - condition:
        character_status:
          alive: false
      goal: "revive_character"
      priority: 100
      
    - condition:
        character_status:
          hp_critically_low: true
          alive: true
      goal: "get_to_safety"
      priority: 99
      
  # Maintenance priorities
  maintenance:
    - condition:
        character_status:
          cooldown_active: true
      goal: "wait_for_cooldown"
      priority: 80
      
  # Material gathering priorities (high priority - before progression)
  material_gathering:
    - condition:
        materials:
          status: ["insufficient", "gathering", "checking"]
        character_status:
          safe: true
      goal: "gather_materials"
      priority: 75
      
    - condition:
        materials:
          status: "gathered_raw"
          gathered: false
        character_status:
          safe: true
      goal: "gather_materials"
      priority: 75
  
  # Progression priorities
  progression:
    - condition:
        character_status:
          safe: true
          hp_sufficient_for_combat: true
      goal: "hunt_monsters"
      priority: 70
      
    - condition:
        equipment_status:
          upgrade_status: ["needs_analysis", "analyzing"]
        character_status:
          safe: true
      goal: "upgrade_weapon"
      priority: 60

# State mapping - defines how complex states map to simple boolean flags
# This replaces the complex formulas and operators
# State mappings removed - moved to state engine code for truly declarative configuration
# Computed boolean flags are now calculated dynamically based on actual data values

# Configuration thresholds - moved from inline expressions
thresholds:
  # Health and safety thresholds (percentages)
  safe_hp_percentage: 30
  combat_hp_percentage: 80
  max_hp_percentage: 100
  critically_low_hp: 30
  
  # Level thresholds
  low_level_threshold: 5
  
  # Combat viability thresholds
  min_combat_win_rate: 0.0
  recency_decay_factor: 0.9
  
  # Search and exploration parameters
  default_search_radius: 2
  max_search_radius: 4
  level_matching_range: 2
  
  # GOAP execution parameters
  max_goap_iterations: 50  # Allow up to 50 actions per goal execution