# GOAP Start State Configuration
# This file defines the default state variables that should be initialized for GOAP planning
# These ensure that all action prerequisites are properly set up for plan generation

# Core GOAP Action Prerequisites - Only variables used by actions in config/actions.yaml
core_states:
  # Character capabilities (required by multiple actions)
  can_move: true
  can_attack: true
  character_safe: true
  character_alive: true
  need_combat: true
  
  # Location states (required for movement and positioning)
  at_target_location: false
  monsters_available: false    # KEY: Set to false so find_monsters is required
  monster_present: false       # KEY: Set to false so find_monsters must run first
  
  # Ensure XP-seeking cycle requirements
  need_combat: true
  
  # Action timing states
  is_on_cooldown: false
  needs_rest: false
  
  # Goal completion states
  has_hunted_monsters: false
  monster_defeated: false
  
  # Equipment and crafting states (required for upgrade_weapon goal)
  need_equipment: true          # Enable equipment-related actions
  has_better_weapon: false      # Goal state
  equipment_equipped: false     # Goal state
  character_stats_improved: false  # Goal state
  best_weapon_selected: false  # Required for equipment progression
  equipment_info_unknown: true # Required for lookup_item_info action
  weapon_crafted: false        # Required for craft_selected_weapon goal
  equipment_ready: false       # Set by execute_crafting_plan action
  
  # Workshop and resource states
  workshops_discovered: false
  need_workshop_discovery: true
  at_workshop: false
  at_correct_workshop: false
  workshop_location_known: false
  need_specific_workshop: false
  
  # Material and inventory states
  has_crafting_materials: false
  need_crafting_materials: true
  has_materials: false
  has_raw_materials: false
  has_refined_materials: false
  materials_sufficient: false
  inventory_updated: false
  
  # Resource location states
  at_resource_location: false
  resource_location_known: false
  resource_found: false
  need_resources: true
  
  # Skill progression states
  need_weaponcrafting_upgrade: false  # Will be computed by state engine
  need_skill_upgrade: false          # Will be computed by state engine
  weaponcrafting_level_sufficient: false
  skill_requirements_checked: false
  
  # Recipe and crafting knowledge states
  recipe_known: false
  craftable_weapon_identified: false
  material_requirements_known: false
  equipment_info_known: false
  craft_plan_available: false
  equipment_analysis_available: false
  crafting_opportunities_known: false
  
  # Map exploration states (for analyze_resources prerequisites)
  map_explored: false

# Metadata
metadata:
  version: "1.0"
  description: "Default GOAP start state initialization for comprehensive action planning"
  created_by: "Claude Code"
  last_updated: "2025-06-29"
  
# Usage Notes:
# - These values provide sensible defaults for GOAP planning
# - Actual runtime state will override these defaults
# - Add new state variables here as new actions are developed
# - Boolean states should default to false for requirements, true for capabilities