# GOAP Action Weights Configuration
#
# This file defines action costs and goal weights for the GOAP planning system.
# Action costs determine planning efficiency, while goal weights determine
# priority in goal selection. All names must match action registry.

action_costs:
  # Movement actions
  move_to_location: 1
  
  # Combat actions
  fight_monster: 3
  
  # Gathering actions
  gather_resource: 2
  gather_copper_ore: 2
  gather_ash_wood: 2
  gather_gudgeon: 3    # Fishing takes longer
  
  # Crafting actions
  craft_item: 4
  craft_weapon: 5
  craft_armor: 5
  craft_tool: 3
  
  # Utility actions
  rest_at_location: 1
  equip_item: 1
  unequip_item: 1
  use_item: 2
  
  # Trading actions
  buy_from_npc: 2
  sell_to_npc: 2
  deposit_bank: 1
  withdraw_bank: 1
  
  # Grand Exchange actions
  ge_buy_item: 3
  ge_sell_item: 3

goal_weights:
  # Progression goals
  reach_level: 100
  gain_experience: 80
  level_skill: 75
  
  # Economic goals
  accumulate_gold: 30
  buy_equipment: 60
  sell_items: 25
  
  # Survival goals
  recover_hp: 150      # Highest priority for emergencies
  equip_better_gear: 70
  
  # Collection goals
  gather_resources: 50
  complete_task: 80
  explore_map: 20
  
  # Crafting goals
  craft_equipment: 75
  upgrade_weapon: 90
  upgrade_armor: 85

# Dynamic weight modifiers based on character state
weight_modifiers:
  low_hp:
    recover_hp: 2.0    # Double priority when HP is low
    
  high_level:
    gather_resources: 0.5  # Reduce gathering priority at high levels
    craft_equipment: 1.5   # Increase crafting priority
    
  low_gold:
    accumulate_gold: 1.5
    sell_items: 2.0
    
  inventory_full:
    sell_items: 3.0
    deposit_bank: 2.0