# State Calculation Engine Configuration
# This file defines rules for dynamic state calculation and response processing

# State calculation rules - replaces hardcoded state computation logic
state_calculation:
  # Character health and safety states
  character_safe:
    formula: "hp_percentage >= ${thresholds.safe_hp_percentage}"
    
  needs_rest:
    formula: "hp_percentage < ${thresholds.rest_hp_percentage}"
    
  can_attack:
    formula: "hp_percentage >= ${thresholds.attack_hp_percentage} and not is_on_cooldown"
    
  can_move:
    formula: "character_hp > 0 and not is_on_cooldown"
    
  # Character progression states  
  need_combat:
    formula: "character_level < ${thresholds.combat_level_threshold}"
    
  needs_xp:
    formula: "xp_percentage < 100"
    
  close_to_levelup:
    formula: "xp_percentage >= ${thresholds.levelup_xp_percentage}"
    
  # Resource and equipment states
  need_resources:
    formula: "character_level < ${thresholds.resource_level_threshold}"
    
  need_equipment:
    formula: "character_level < ${thresholds.equipment_level_threshold}"
    
  need_crafting_materials:
    formula: "not has_crafting_materials"
    
  need_workshop_discovery:
    formula: "not workshops_discovered and character_level >= 2"
    
  has_equipment:
    formula: "character_level >= ${thresholds.equipment_level_threshold}"
    
  # Recipe and crafting planning states  
  equipment_info_unknown:
    formula: "need_equipment and not best_weapon_selected"  # Look up recipes only if equipment needed and no weapon selected yet
    
  recipe_known:
    formula: "best_weapon_selected"  # Recipe is known after weapon selection
    
  # Smelting and material processing states
  need_refined_materials:
    formula: "smelting_required == true"
    
  equipment_equipped:
    formula: "character_level >= 2"
    
  character_stats_improved:
    formula: "character_level >= 2"
    
# Computed states that require complex logic
computed_states:
  is_on_cooldown:
    type: "cooldown_check"
    
  character_alive:
    type: "formula"
    formula: "character_hp > 0"
    
  # Equipment progression computed states
  need_weapon_upgrade:
    type: "equipment_analysis"
    analysis_type: "weapon_upgrade"
    threshold_config: "weapon_upgrade_thresholds"
    
  need_armor_upgrade:
    type: "equipment_analysis"
    analysis_type: "armor_upgrade"
    threshold_config: "armor_upgrade_thresholds"
    
  need_complete_equipment:
    type: "equipment_analysis"
    analysis_type: "complete_equipment"
    threshold_config: "equipment_completion_thresholds"
    
    
  need_workshop_discovery:
    type: "workshop_analysis"
    analysis_type: "discovery_needed"
    threshold_config: "workshop_discovery_thresholds"
    
  need_specific_workshop:
    type: "workshop_analysis"
    analysis_type: "specific_workshop_needed"
    threshold_config: "specific_workshop_thresholds"
    
  # Equipment status states
  has_better_weapon:
    type: "equipment_check"
    check_type: "weapon_improved"
    
  has_better_armor:
    type: "equipment_check"
    check_type: "armor_improved"
    
  has_complete_equipment_set:
    type: "equipment_check"
    check_type: "set_complete"
    
  has_crafting_materials:
    type: "inventory_check"
    check_type: "materials_available"
    
  workshops_discovered:
    type: "knowledge_check"
    check_type: "workshops_known"
    
  # Location and crafting states
  at_workshop:
    type: "location_check"
    check_type: "workshop_location"
    
  at_correct_workshop:
    type: "location_check"
    check_type: "correct_workshop_location"
    
  at_resource_location:
    type: "location_check"
    check_type: "resource_location"
    
  has_materials:
    type: "inventory_check"
    check_type: "required_materials"
    
  materials_sufficient:
    type: "inventory_check"
    check_type: "sufficient_quantity"
    
  # General material checks for crafting workflows
  has_raw_materials:
    type: "inventory_check"
    check_type: "raw_materials_available"
    
  has_refined_materials:
    type: "inventory_check" 
    check_type: "refined_materials_available"
    
  material_requirements_known:
    type: "knowledge_check"
    check_type: "material_requirements_discovered"
    
  best_weapon_selected:
    type: "knowledge_check"
    check_type: "optimal_weapon_identified"
    
  craftable_weapon_identified:
    type: "knowledge_check" 
    check_type: "craftable_weapon_found"
    
  # Skill progression states
  need_weaponcrafting_upgrade:
    type: "computed"
    method: "check_weaponcrafting_upgrade_needed"
    
  need_skill_upgrade:
    type: "computed"
    method: "check_skill_upgrade_needed"
    
  weaponcrafting_level_sufficient:
    type: "computed"
    method: "check_weaponcrafting_level_sufficient"

# Response processing rules - replaces hardcoded update_world_state_from_response logic
response_handlers:
  move:
    at_target_location:
      type: "static"
      value: true
    character_x:
      type: "response_field"
      field: "data.character.x"
    character_y:
      type: "response_field"
      field: "data.character.y"
    monster_present:
      type: "conditional"
      condition:
        type: "state_check"
        state_key: "monsters_available"
        value: false
      true_value: false
      false_value: true  # Keep monster_present if monsters are available
      
  find_monsters:
    monsters_available:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    monster_present:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    at_target_location:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: true
      false_value: false  # Need to move to monster location
      
  attack:
    monster_present:
      type: "static"
      value: false
    has_hunted_monsters:
      type: "conditional"
      condition:
        type: "response_field"
        field: "data.fight.result"
        value: "win"
      true_value: true
      false_value: true  # Mark as hunted regardless of result
    monsters_available:
      type: "conditional"
      condition:
        type: "response_field"
        field: "data.fight.result"
        value: "win"
      true_value: false
      false_value: false
    monster_defeated:
      type: "conditional"
      condition:
        type: "response_field"
        field: "data.fight.result"
        value: "win"
      true_value: true
      false_value: false
      
  rest:
    character_safe:
      type: "computation"
      method: "calculate_hp_safety"
    needs_rest:
      type: "computation"
      method: "calculate_rest_need"
      
  wait:
    is_on_cooldown:
      type: "static"
      value: false
    can_move:
      type: "static"
      value: true
    can_attack:
      type: "static"
      value: true
      
  # Equipment progression response handlers
  gather_resources:
    has_resources:
      type: "conditional"
      condition:
        type: "response_field"
        field: "data.details.items"
        value: null
      true_value: false
      false_value: true
    inventory_updated:
      type: "static"
      value: true
    at_resource_location:
      type: "static"
      value: true
      
  find_resources:
    resource_location_known:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    at_resource_location:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: true
      false_value: false
      
  craft_item:
    has_equipment:
      type: "conditional"
      condition:
        type: "response_field"
        field: "data.details.items"
        value: null
      true_value: false
      false_value: true
    inventory_updated:
      type: "static"
      value: true
    at_workshop:
      type: "static"
      value: true
      
  equip_item:
    equipment_equipped:
      type: "static"
      value: true
    character_stats_improved:
      type: "computation"
      method: "calculate_stat_improvement"
    inventory_updated:
      type: "static"
      value: true
      
  unequip_item:
    equipment_equipped:
      type: "static"
      value: false
    inventory_updated:
      type: "static"
      value: true
      
  analyze_resources:
    equipment_analysis_available:
      type: "static"
      value: true
    crafting_opportunities_known:
      type: "static"
      value: true
      
  lookup_item_info:
    equipment_info_known:
      type: "static"
      value: true
    craft_plan_available:
      type: "static"
      value: true
    recipe_known:
      type: "static"
      value: true
      
  smelt_materials:
    has_refined_materials:
      type: "conditional"
      condition:
        type: "response_field"
        field: "success"
      true_value: true
      false_value: false
    inventory_updated:
      type: "static"
      value: true
    equipment_info_unknown:
      type: "static"
      value: false
      
  find_correct_workshop:
    at_correct_workshop:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    workshops_discovered:
      type: "static"
      value: true
    workshop_location_known:
      type: "static"
      value: true
    need_specific_workshop:
      type: "static"
      value: false
      
  transform_material:
    has_refined_materials:
      type: "conditional"
      condition:
        type: "response_field"
        field: "success"
      true_value: true
      false_value: false
    inventory_updated:
      type: "static"
      value: true
      
  find_workshops:
    workshops_discovered:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    workshop_location_known:
      type: "conditional"
      condition:
        type: "response_field"
        field: "location"
        value: null
      true_value: false
      false_value: true
    at_workshop:
      type: "static"
      value: false
      
  evaluate_weapon_recipes:
    equipment_info_known:
      type: "static"
      value: true
    recipe_known:
      type: "static"
      value: true
    best_weapon_selected:
      type: "conditional"
      condition:
        type: "response_field"
        field: "selected_weapon"
        value: null
      true_value: false
      false_value: true
    craftable_weapon_identified:
      type: "conditional"
      condition:
        type: "response_field"
        field: "selected_weapon"
        value: null
      true_value: false
      false_value: true

# World state update patterns
world_state_updates:
  # Common update patterns that can be reused
  movement_update:
    at_target_location: true
    
  combat_victory:
    monster_present: false
    monster_defeated: true
    has_hunted_monsters: true
    
  combat_defeat:
    monster_present: false
    has_hunted_monsters: true
    
  rest_recovery:
    character_safe: true
    needs_rest: false