validation_rules:
  global: []
  actions:
    equip:
    - type: valid_client
    - type: required_params
      params:
      - item_code
    - type: valid_item
      param: item_code
    - type: character_alive
    move:
    - type: valid_client
    - type: required_params
      params:
      - x
      - y
    - type: valid_coordinates
      params:
      - x
      - y
    - type: not_at_location
      params:
      - x
      - y
    - type: character_alive
    attack:
    - type: valid_client
    - type: character_alive
    - type: character_hp_above
      threshold: 10
    gather:
    - type: valid_client
    - type: character_alive
    gather_resources:
    - type: valid_client
    - type: character_alive
    - type: location_has_content
      content_type: resource
    - type: resource_matches_target
      param: target_resource
    rest:
    - type: valid_client
    - type: character_alive
    craft:
    - type: valid_client
    - type: required_params
      params:
      - recipe_code
    - type: character_alive
    craft_item:
    - type: valid_client
    - type: required_params
      params:
      - item_code
    - type: character_alive
    - type: location_has_content
      content_type: workshop
    - type: workshop_compatible
      param: item_code
    bank_deposit:
    - type: valid_client
    - type: required_params
      params:
      - item_code
      - quantity
    - type: valid_item
      param: item_code
    - type: character_alive
    bank_withdraw:
    - type: valid_client
    - type: required_params
      params:
      - item_code
      - quantity
    - type: valid_item
      param: item_code
    - type: character_alive
    buy:
    - type: valid_client
    - type: required_params
      params:
      - item_code
      - quantity
    - type: valid_item
      param: item_code
    - type: character_alive
    sell:
    - type: valid_client
    - type: required_params
      params:
      - item_code
      - quantity
    - type: valid_item
      param: item_code
    - type: character_alive
    use_item:
    - type: valid_client
    - type: required_params
      params:
      - item_code
    - type: valid_item
      param: item_code
    - type: character_alive
    unequip:
    - type: valid_client
    - type: required_params
      params:
      - slot
    - type: character_alive
    complete_task:
    - type: valid_client
    - type: character_alive
    accept_task:
    - type: valid_client
    - type: required_params
      params:
      - task_code
    - type: character_alive
    recycle:
    - type: valid_client
    - type: required_params
      params:
      - item_code
      - quantity
    - type: valid_item
      param: item_code
    - type: character_alive
    analyze_combat_viability:
    - type: valid_client
    - type: character_alive
    analyze_crafting_chain:
    - type: valid_client
    - type: character_alive
    analyze_crafting_requirements:
    - type: valid_client
    - type: character_alive
    analyze_equipment:
    - type: valid_client
    - type: character_alive
    analyze_knowledge_state:
    - type: valid_client
    - type: character_alive
    analyze_resources:
    - type: valid_client
    - type: character_alive
    analyze_workshop_requirements:
    - type: valid_client
    - type: character_alive
    check_inventory:
    - type: valid_client
    - type: character_alive
    check_location:
    - type: valid_client
    - type: character_alive
    check_skill_requirement:
    - type: valid_client
    - type: character_alive
    evaluate_weapon_recipes:
    - type: valid_client
    - type: character_alive
    find_correct_workshop:
    - type: valid_client
    - type: character_alive
    find_resources:
    - type: valid_client
    - type: character_alive
    find_xp_sources:
    - type: valid_client
    - type: character_alive
    move_to_resource:
    - type: valid_client
    - type: required_params
      params:
      - target_x
      - target_y
    - type: valid_coordinates
      params:
      - target_x
      - target_y
    - type: character_alive
    move_to_workshop:
    - type: valid_client
    - type: required_params
      params:
      - target_x
      - target_y
    - type: valid_coordinates
      params:
      - target_x
      - target_y
    - type: character_alive
    transform_raw_materials:
    - type: valid_client
    - type: character_alive
    upgrade_weaponcrafting_skill:
    - type: valid_client
    - type: character_alive
    lookup_item_info:
    - type: valid_client
    - type: required_params
      params:
      - item_code
    - type: character_alive
validation_messages:
  required_params: 'Missing required parameter(s): {missing}'
  valid_coordinates: 'Invalid coordinates: {details}'
  character_alive: Character must be alive to perform this action
  not_at_location: Character is already at the target location
  valid_item: Invalid or missing item code
  character_hp_above: Character HP too low for this action
  valid_client: No API client provided
