import Formal.Extracted.CombatPicker
import Formal.Extracted.NearestTile
import Formal.Extracted.NpcBuyCore
import Formal.CombatTargetExistence
import Formal.NearestTile
import Formal.NpcBuyInventory

/-!
# Extracted ↔ hand-model bridge lemmas (P1, docs/PLAN_mechanical_extraction.md)

HAND-WRITTEN. Each theorem proves a mechanically-extracted definition
(`Formal/Extracted/*.lean`, regenerated by `scripts/extract_lean.py`) equal to
the pre-existing hand model it replaces as the trusted definition. Python
drift ⇒ regeneration changes the extracted def ⇒ these proofs break ⇒ gate red.

* `nearest_tile_bridge` — pointwise equality on the SHARED encoding
  (`List (Int × Int)`): the extracted argmin (Int-valued `abs`, Bool lex key)
  IS `Formal.NearestTile.nearestTile` (Nat manhattan, Prop lex key).
* `combat_picker_bridge` — the hand model codes monsters as `Int`, Python as
  `str`; the encoding `encMonster f = (f m.code, m.level)` (any `f : Int →
  String` — codes are pure payload) commutes: `extracted ∘ encode = encode ∘
  handModel` for ALL predicate oracles.
* `npc_buy_is_applicable_bridge` — pointwise on the Nat encoding UNDER the
  standing wellformedness invariant `used ≤ cap` (every safety contract in
  `Formal.NpcBuyInventory` carries the same `hwf`). The two sides genuinely
  diverge OUTSIDE it: at `used > cap ∧ quantity = 0` Python refuses
  (`free` is negative) while the hand model's Nat truncation accepts —
  kernel-pinned by `npc_buy_is_applicable_divergence_outside_wf` rather than
  silently bent. Production states always satisfy `used ≤ cap`.
* `npc_buy_apply_delta` / `npc_buy_apply_bridge` — the extracted per-key dict
  update mints exactly `+quantity` of total value (`sumValues` encoding),
  commuting with the hand model's slot-projection `apply`.

NO sorry / admit / extra axioms (gate-enforced).
-/

namespace Extracted.Bridges

/-! ## NearestTile: extracted `nearest_tile` = hand `nearestTile`. -/

/-- The extracted Bool lex key agrees with the hand model's Prop `keyLt`
(Int-encoded `abs`-sum vs Nat `manhattan`). -/
private theorem lexLt3_iff (ox oy : Int) (a b : Int × Int) :
    Extracted.NearestTile._lexLt3
        ((Extracted.NearestTile._intAbs (a.1 - ox)) + (Extracted.NearestTile._intAbs (a.2 - oy)),
          a.1, a.2)
        ((Extracted.NearestTile._intAbs (b.1 - ox)) + (Extracted.NearestTile._intAbs (b.2 - oy)),
          b.1, b.2) = true
      ↔ Formal.NearestTile.keyLt ox oy a b := by
  simp only [Extracted.NearestTile._lexLt3, Extracted.NearestTile._intAbs,
    Formal.NearestTile.keyLt, Formal.NearestTile.manhattan,
    Bool.or_eq_true, Bool.and_eq_true, decide_eq_true_eq, Int.ofNat_eq_natCast]
  omega

/-- The extracted fold step is exactly the hand model's `minStep`. -/
private theorem extStep_eq (ox oy : Int) :
    (fun (best x : Int × Int) =>
        if Extracted.NearestTile._lexLt3
            ((Extracted.NearestTile._intAbs (x.1 - ox)) + (Extracted.NearestTile._intAbs (x.2 - oy)),
              x.1, x.2)
            ((Extracted.NearestTile._intAbs (best.1 - ox)) + (Extracted.NearestTile._intAbs (best.2 - oy)),
              best.1, best.2)
        then x else best)
      = Formal.NearestTile.minStep ox oy := by
  funext best x
  unfold Formal.NearestTile.minStep
  by_cases h : Formal.NearestTile.keyLt ox oy x best
  · rw [if_pos ((lexLt3_iff ox oy x best).mpr h), if_pos h]
  · rw [if_neg (fun hc => h ((lexLt3_iff ox oy x best).mp hc)), if_neg h]

/-- BRIDGE: the extracted selector equals the hand model pointwise on the
shared `List (Int × Int)` encoding — every theorem in `Formal.NearestTile`
(totality, membership, lex-min determinism, least-cost) transfers. -/
theorem nearest_tile_bridge (ox oy : Int) (tiles : List (Int × Int)) :
    Extracted.NearestTile.nearest_tile ox oy tiles
      = Formal.NearestTile.nearestTile ox oy tiles := by
  cases tiles with
  | nil => rfl
  | cons h t =>
    show (if (decide ((Int.ofNat (List.length (h :: t))) = 0))
          then none
          else (Extracted.NearestTile._minByKey3
            (fun u => (((Extracted.NearestTile._intAbs ((u.1) - ox))
                          + (Extracted.NearestTile._intAbs ((u.2) - oy))), (u.1), (u.2)))
            (h :: t)))
        = Formal.NearestTile.nearestTile ox oy (h :: t)
    rw [if_neg (by simp only [decide_eq_true_eq, Int.ofNat_eq_natCast, List.length_cons]; omega)]
    simp only [Extracted.NearestTile._minByKey3, Formal.NearestTile.nearestTile]
    rw [extStep_eq ox oy]

/-! ## NpcBuyCore: extracted cores = hand `Formal.NpcBuyInventory`. -/

/-- Total minted value of an association-list inventory — the encoding from
the extracted per-key dict to the hand model's slot projection `used`. -/
def sumValues : List (String × Int) → Int
  | [] => 0
  | kv :: rest => kv.2 + sumValues rest

/-- The extracted `apply` mints EXACTLY `+quantity` of total value (every
other entry preserved — the same contract `Formal.NpcBuyInventory.apply`
states on the slot projection). -/
theorem npc_buy_apply_delta (inv : List (String × Int)) (k : String) (q : Int) :
    sumValues (Extracted.NpcBuyCore.npc_buy_apply_pure inv k q) = sumValues inv + q := by
  unfold Extracted.NpcBuyCore.npc_buy_apply_pure
  induction inv with
  | nil =>
    simp [Extracted.NpcBuyCore._dictSet, Extracted.NpcBuyCore._dictGetD, sumValues]
  | cons kv rest ih =>
    by_cases hk : (kv.1 == k) = true
    · simp [Extracted.NpcBuyCore._dictSet, Extracted.NpcBuyCore._dictGetD, sumValues, hk]
      omega
    · simp only [Extracted.NpcBuyCore._dictSet, Extracted.NpcBuyCore._dictGetD, sumValues,
        Bool.not_eq_true] at *
      simp [hk, sumValues, ih]
      omega


/-- BRIDGE (apply): the extracted dict update commutes with the hand model's
slot-projection `apply` through the `sumValues` encoding. -/
theorem npc_buy_apply_bridge (inv : List (String × Int)) (item_code : String)
    (used cap q : Nat) (henc : sumValues inv = (used : Int)) :
    sumValues (Extracted.NpcBuyCore.npc_buy_apply_pure inv item_code (q : Int))
      = ((Formal.NpcBuyInventory.apply ⟨used, cap⟩ q).used : Int) := by
  rw [npc_buy_apply_delta, henc]
  simp [Formal.NpcBuyInventory.apply]

/-- BRIDGE (is_applicable): pointwise equal on the Nat encoding under the
standing wellformedness invariant `used ≤ cap` (the hypothesis every
`Formal.NpcBuyInventory` safety contract already carries). -/
theorem npc_buy_is_applicable_bridge (used cap q gold price : Nat) (hwf : used ≤ cap) :
    Extracted.NpcBuyCore.npc_buy_is_applicable_pure (used : Int) (cap : Int)
        (q : Int) (gold : Int) (price : Int)
      = Formal.NpcBuyInventory.isApplicable ⟨used, cap⟩ q gold price := by
  unfold Extracted.NpcBuyCore.npc_buy_is_applicable_pure Formal.NpcBuyInventory.isApplicable
  by_cases h1 : ((cap : Int) - (used : Int) < (q : Int))
  · have h1' : ¬ (q ≤ cap - used) := by omega
    rw [if_pos (decide_eq_true h1)]
    simp [h1']
  · have h1' : q ≤ cap - used := by omega
    rw [if_neg (fun hc => h1 (of_decide_eq_true hc))]
    simp [h1']
    rw [decide_eq_decide.mpr (show ((gold : Int) < (price : Int) * (q : Int))
          ↔ ¬ (price * q ≤ gold) from by rw [← Int.natCast_mul]; omega),
      decide_not]

/-- HONEST BOUNDARY (kernel-pinned, NOT bridged): outside the wellformedness
domain — `used > cap` with `quantity = 0` — Python (= extracted) REFUSES
(`free` is negative, `free < 0` fails the slot floor) while the hand model's
Nat-truncating `cap - used = 0` ACCEPTS `0 ≤ 0`. The bridge above therefore
carries `hwf : used ≤ cap`; production `WorldState` maintains it invariantly. -/
theorem npc_buy_is_applicable_divergence_outside_wf :
    Extracted.NpcBuyCore.npc_buy_is_applicable_pure 12 10 0 5 1 = false
      ∧ Formal.NpcBuyInventory.isApplicable ⟨12, 10⟩ 0 5 1 = true := by
  constructor <;> decide

/-! ## CombatPicker: extracted picker = hand `pickWinnableWindowed`. -/

open Formal.CombatTargetExistence in
/-- Monster encoding: the hand model codes monsters as `Int`, Python as `str`.
Codes are pure payload (never compared, only carried), so ANY `f : Int →
String` yields a faithful embedding of the hand model's input space. -/
def encMonster (f : Int → String) (m : Monster) : String × Int :=
  (f m.code, m.level)

open Formal.CombatTargetExistence in
/-- The two generated fold steps, named for the proofs below. `eStepW` is the
window tier of the extracted picker (defeq to the generated lambda after
zeta-substituting `min_level`/`max_level`). -/
private def eStepW (L : Int) (wc : String → Bool) :
    Option (String × Int) → String × Int → Option (String × Int) :=
  fun best _x =>
    let code := _x.1
    let level := _x.2
    if (!((decide ((max 1 (L - 1)) ≤ level)) && (decide (level ≤ (L + 2))))) then best
    else if (!(wc code)) then best
    else
      match best with
      | none => some (code, level)
      | some best_1 => if (decide (level > (best_1.2))) then some (code, level) else best

open Formal.CombatTargetExistence in
/-- The fallback tier of the extracted picker. -/
private def eStepF (L : Int) (wc xc : String → Bool) :
    Option (String × Int) → String × Int → Option (String × Int) :=
  fun best _x =>
    let code := _x.1
    let level := _x.2
    if ((decide (level > (L + 2))) || (!(xc code)) || (!(wc code))) then best
    else
      match best with
      | none => some (code, level)
      | some best_3 => if (decide (level > (best_3.2))) then some (code, level) else best

open Formal.CombatTargetExistence in
/-- Generic transfer: a fold step that mirrors one `pickBest` transition step
through the encoding makes the whole left fold equal `pickBest`. -/
private theorem foldl_eq_pickBest (f : Int → String) (p : WinnableFn)
    (F : Option (String × Int) → String × Int → Option (String × Int))
    (hF : ∀ (acc : Option Monster) (m : Monster),
        F (acc.map (encMonster f)) (encMonster f m) =
          if p m then
            (match acc with
             | none => some (encMonster f m)
             | some b =>
               if m.level > b.level then some (encMonster f m) else some (encMonster f b))
          else acc.map (encMonster f)) :
    ∀ (ms : List Monster) (acc : Option Monster),
      List.foldl F (acc.map (encMonster f)) (ms.map (encMonster f))
        = (pickBest p acc ms).map (encMonster f) := by
  intro ms
  induction ms with
  | nil => intro acc; rfl
  | cons m rest ih =>
    intro acc
    rw [List.map_cons, List.foldl_cons, hF acc m]
    cases hp : p m with
    | false =>
      simp only [Bool.false_eq_true, if_false]
      rw [ih acc]
      simp [pickBest, hp]
    | true =>
      simp only [if_true]
      cases acc with
      | none =>
        have h2 : pickBest p none (m :: rest) = pickBest p (some m) rest := by
          simp [pickBest, hp]
        rw [h2]
        have h3 := ih (some m)
        simpa using h3
      | some b =>
        by_cases hl : m.level > b.level
        · have h2 : pickBest p (some b) (m :: rest) = pickBest p (some m) rest := by
            simp [pickBest, hp, hl]
          rw [h2]
          have h3 := ih (some m)
          simpa [hl] using h3
        · have h2 : pickBest p (some b) (m :: rest) = pickBest p (some b) rest := by
            simp [pickBest, hp, hl]
          rw [h2]
          have h3 := ih (some b)
          simpa [hl] using h3

open Formal.CombatTargetExistence in
/-- The extracted window-tier step mirrors `pickBest` with the predicate
`winnable ∧ in-window` — the exact tier-1 predicate of the hand model. -/
private theorem hF_window (L : Int) (f : Int → String) (wc : String → Bool) :
    ∀ (acc : Option Monster) (m : Monster),
      eStepW L wc (acc.map (encMonster f)) (encMonster f m) =
        if (fun m => wc (f m.code) && inWindow L m) m then
          (match acc with
           | none => some (encMonster f m)
           | some b =>
             if m.level > b.level then some (encMonster f m) else some (encMonster f b))
        else acc.map (encMonster f) := by
  intro acc m
  unfold eStepW encMonster
  by_cases hwin : ((max 1 (L - 1)) ≤ m.level ∧ m.level ≤ (L + 2))
  · by_cases hwc : wc (f m.code) = true
    · cases acc with
      | none => simp [inWindow, hwin, hwc]
      | some b =>
        by_cases hl : m.level > b.level
        · simp [inWindow, hwin, hwc, hl]
        · simp [inWindow, hwin, hwc, hl]
    · cases acc with
      | none => simp [inWindow, hwin, hwc]
      | some b => simp [inWindow, hwin, hwc]
  · have hwinb : inWindow L m = false := by
      simp [inWindow, hwin]
    have hsplit : ¬ ((max 1 (L - 1)) ≤ m.level) ∨ ¬ (m.level ≤ (L + 2)) := by
      by_cases ha : (max 1 (L - 1)) ≤ m.level
      · exact Or.inr (fun hb => hwin ⟨ha, hb⟩)
      · exact Or.inl ha
    cases acc with
    | none =>
      rcases hsplit with hs | hs <;> simp [hwinb, hs]
    | some b =>
      rcases hsplit with hs | hs <;> simp [hwinb, hs]

open Formal.CombatTargetExistence in
/-- The extracted fallback-tier step mirrors `pickBest` with the predicate
`winnable ∧ xp-positive ∧ not-overleveled` — the hand model's tier 2. -/
private theorem hF_fallback (L : Int) (f : Int → String) (wc xc : String → Bool) :
    ∀ (acc : Option Monster) (m : Monster),
      eStepF L wc xc (acc.map (encMonster f)) (encMonster f m) =
        if (fun m => wc (f m.code) && xc (f m.code) && notOverleveled L m) m then
          (match acc with
           | none => some (encMonster f m)
           | some b =>
             if m.level > b.level then some (encMonster f m) else some (encMonster f b))
        else acc.map (encMonster f) := by
  intro acc m
  unfold eStepF encMonster
  by_cases hno : m.level ≤ L + 2
  · have hgt : ¬ (m.level > L + 2) := by omega
    by_cases hwc : wc (f m.code) = true
    · by_cases hxc : xc (f m.code) = true
      · cases acc with
        | none => simp [notOverleveled, hno, hgt, hwc, hxc]
        | some b =>
          by_cases hl : m.level > b.level
          · simp [notOverleveled, hno, hgt, hwc, hxc, hl]
          · simp [notOverleveled, hno, hgt, hwc, hxc, hl]
      · cases acc with
        | none => simp [notOverleveled, hno, hgt, hwc, hxc]
        | some b => simp [notOverleveled, hno, hgt, hwc, hxc]
    · cases acc with
      | none => simp [notOverleveled, hno, hgt, hwc]
      | some b => simp [notOverleveled, hno, hgt, hwc]
  · have hgt : m.level > L + 2 := by omega
    have hnob : notOverleveled L m = false := by
      simp [notOverleveled]
      omega
    cases acc with
    | none => simp [hnob, hgt]
    | some b => simp [hnob, hgt]

open Formal.CombatTargetExistence in
/-- BRIDGE: the extracted picker commutes with the hand model
`pickWinnableWindowed` through the monster encoding, for EVERY level, every
code embedding `f`, and every pair of predicate oracles — `extracted ∘ encode
= encode ∘ handModel`. All `Formal.CombatTargetExistence` liveness theorems
(window preference, fallback existence, honest-`none`) transfer. -/
theorem combat_picker_bridge (L : Int) (f : Int → String) (wc xc : String → Bool)
    (ms : List Monster) :
    Extracted.CombatPicker.pick_winnable_monster_pure L (ms.map (encMonster f)) wc xc
      = (pickWinnableWindowed L (fun m => wc (f m.code)) (fun m => xc (f m.code)) ms).map
          (fun m => f m.code) := by
  show (match List.foldl (eStepW L wc) ((none : Option Monster).map (encMonster f))
              (ms.map (encMonster f)) with
        | some best_2 => some best_2.1
        | none =>
          match List.foldl (eStepF L wc xc)
                  (List.foldl (eStepW L wc) ((none : Option Monster).map (encMonster f))
                    (ms.map (encMonster f)))
                  (ms.map (encMonster f)) with
          | some best_4 => some best_4.1
          | none => none)
      = (pickWinnableWindowed L (fun m => wc (f m.code)) (fun m => xc (f m.code)) ms).map
          (fun m => f m.code)
  rw [foldl_eq_pickBest f (fun m => wc (f m.code) && inWindow L m) (eStepW L wc)
        (hF_window L f wc) ms none]
  unfold pickWinnableWindowed pickWinnable
  cases hpw : pickBest (fun m => wc (f m.code) && inWindow L m) none ms with
  | some b => simp [encMonster]
  | none =>
    simp only [Option.map_none]
    have hfall := foldl_eq_pickBest f
        (fun m => wc (f m.code) && xc (f m.code) && notOverleveled L m)
        (eStepF L wc xc) (hF_fallback L f wc xc) ms none
    simp only [Option.map_none] at hfall
    rw [hfall]
    cases hpf : pickBest
        (fun m => wc (f m.code) && xc (f m.code) && notOverleveled L m) none ms with
    | some b2 => simp [encMonster]
    | none => simp

end Extracted.Bridges
