import Formal.CalculatePath
import Formal.TaskBatch
import Formal.InventoryCaps
import Formal.InventoryProfile
import Formal.PredictWin
import Formal.LoadoutProjection
import Formal.EquipmentScoring
import Formal.SkillXpCurve
import Formal.RecipeClosure
import Formal.TaskFeasibility
import Formal.TaskReservation
import Formal.PrerequisiteGraph
import Formal.Objective
import Formal.StrategyTraversal
import Formal.BankSelection
import Formal.StuckDetector
import Formal.PriorityBand
import Formal.OwnedCount
import Formal.UpgradeSelection
import Formal.Scalarizer
import Formal.PlannerAdmissibility
import Formal.PlannerDepthBound
import Formal.TieredSelection
import Formal.GearLatch
import Formal.ArbiterSelect
import Formal.TaskDecision
import Formal.WeightedRemaining
import Formal.LowYieldCancel
import Formal.StrategyBlend
import Formal.DecideKey
import Formal.ProgressionReserve
import Formal.CyclesForProgress
import Formal.GatherApply
import Formal.GatherSelection
import Formal.ShoppingList
import Formal.MonsterDropSelection
import Formal.CraftVsBuy
import Formal.LiquidationVenue
import Formal.BuySourceVenue
import Formal.NearestTile
import Formal.ConsumableSelection
import Formal.BankExpansionTiming
import Formal.EventWindow
import Formal.NpcBuyInventory
import Formal.Extracted.CombatPicker
import Formal.Extracted.NearestTile
import Formal.Extracted.NpcBuyCore
import Formal.Extracted.PriorityBand
import Formal.Extracted.ShoppingList
import Formal.Extracted.ArbiterSelect
import Formal.Extracted.RecipeClosure
import Formal.Extracted.TaskBatch
import Formal.Extracted.TaskReservation
import Formal.Extracted.InventoryCaps
import Formal.Extracted.CyclesForProgress
import Formal.Extracted.ScalarCore
import Formal.Extracted.MinGathers
import Formal.Extracted.GatherFloor
import Formal.Extracted.MinCrafts
import Formal.Extracted.MinPlanLength
import Formal.Extracted.EquipmentScoring
import Formal.Extracted.EquipValue
import Formal.Extracted.Bridges
import Formal.Extracted.Bridges2
import Formal.Extracted.Bridges3
import Formal.Extracted.Bridges4
import Formal.Extracted.Bridges5
import Formal.Extracted.Bridges6
import Formal.Extracted.Bridges7
import Formal.Extracted.Bridges8
import Formal.Extracted.SkillTargetCurve
import Formal.Extracted.SkillGrindSelection
import Formal.InventoryChainSafe
import Formal.Contracts
import Formal.ActionCostNonneg
import Formal.RealizableLoadout
import Formal.ApplyBaseline
import Formal.Phase7Invariants
import Formal.Phase8Invariants
import Formal.StoreWarmup
import Formal.GameDataAccessors
import Formal.Phase10GoalLattices
import Formal.WinnableCascade
import Formal.CheapestPath
import Formal.GoalValueBands
import Formal.GoalSystem
-- De-Mathlib'd safety modules (core-only; quarantine compliant).
import Formal.GuardCoverage
import Formal.ActionSetCompleteness
import Formal.ActionApplicability
import Formal.CombatTargetExistence
import Formal.StepDispatch
import Formal.CycleInvariants
import Formal.NoActionDeadlock
import Formal.MultiCycleLiveness
import Formal.EquipValueAugmented
import Formal.GearPolicy
import Formal.RankingComposition
import Formal.PersonalityGrounding
import Formal.PurposeRouting
import Formal.FallbackChain
import Formal.TaskTradeReadyPriority
import Formal.AcceptTaskGate
import Formal.WithdrawSetExpansion
import Formal.RecycleProtection
import Formal.LivenessChain
import Formal.Liveness.Placeholder
import Formal.Liveness.TaskLifecyclePhase
import Formal.Liveness.Measure
import Formal.Liveness.FightProgress
import Formal.Liveness.GatherProgress
import Formal.Liveness.DepositProgress
import Formal.Liveness.RestProgress
import Formal.Liveness.ProgressAction
import Formal.Liveness.MeansKind
import Formal.Liveness.ProductionLadder
import Formal.Liveness.LadderEval
import Formal.Liveness.MeansFiring
import Formal.Liveness.NoDeadlockV2
import Formal.Liveness.PlanAction
import Formal.Liveness.Plan
import Formal.Liveness.PlanExists
import Formal.Liveness.CycleStep
import Formal.Liveness.LIV003Decomposition
import Formal.Liveness.TaskInfeasibility
import Formal.Liveness.CumulativeProgress
import Formal.Liveness.TaskCompleteReachable
import Formal.Liveness.SkillGapClosure
import Formal.Liveness.RecipeChainClosure
import Formal.Liveness.ItemsTaskTermination
import Formal.Liveness.ItemsTaskRun
import Formal.Liveness.GameDataFixture
import Formal.Liveness.LevelFiftyReachable
import Formal.Liveness.LifecycleBound
import Formal.Liveness.LifecycleBound2
import Formal.Liveness.LifecycleBound3
import Formal.Liveness.LifecycleBound4
import Formal.Liveness.TaskPoolSemantics
import Formal.Liveness.TaskPoolTrajectory
import Formal.Liveness.LifecycleBound6
import Formal.Liveness.ApplyXpLevelPreservation
import Formal.Liveness.CycleStepCharacterization
import Formal.Liveness.XpMonotonicity
import Formal.Liveness.LifecycleBound7
import Formal.Liveness.GameDataInvariance
import Formal.Liveness.CategoryBBridge
import Formal.Liveness.PursueTaskSelection
import Formal.Liveness.InProgressDecidesWithSelection
import Formal.Liveness.InventorySemantics
import Formal.Liveness.EquipmentSemantics
import Formal.Liveness.PositionSemantics
import Formal.Liveness.GoldSemantics
import Formal.Liveness.Skill
import Formal.Liveness.SkillXpSemantics
import Formal.Liveness.RichApplyConsistency
import Formal.Liveness.LearningStoreBridge
import Formal.Liveness.MetaGoalDispatch
import Formal.Liveness.StateFieldGapSemantics
import Formal.SkillTargetCurve
import Formal.SkillGrindSelection
import Formal.Extracted.SkillStepDispatch
import Formal.SkillStepDispatch
import Formal.GrindLadder
import Formal.MonsterDropApply
import Formal.Liveness.ReducedReachability
import Formal.Liveness.NoWait
import Formal.Liveness.PerceptionInvariant
import Formal.Liveness.FightFairness
import Formal.Liveness.BlockerQuieting
import Formal.Liveness.BlockerMonotone
import Formal.Liveness.BlockerSelection
import Formal.Liveness.BootstrapReach
import Formal.Liveness.PerceptionRefresh
import Formal.Liveness.CycleStepP
import Formal.Liveness.LevelFiftyReachableP
import Formal.Liveness.BlockerSettled
import Formal.Liveness.SettledWitness
import Formal.Liveness.SettledReach
import Formal.Liveness.InventoryPressure
import Formal.Liveness.InventoryDynamics
import Formal.Liveness.CycleStepF
import Formal.Liveness.CycleStepFIteration
import Formal.Liveness.MeasureDescent
import Formal.Liveness.LevelingDescent
import Formal.Liveness.WarmupCleared
import Formal.Liveness.Leveling
import Formal.Liveness.FightReady
import Formal.Liveness.FightReadyReach
import Formal.Liveness.GearTierLeveling
import Formal.DoomedMemo
import Formal.SkillGateFastFail
import Formal.PlanModel
