import Formal
open Formal.CalculatePath Formal.TaskBatch Formal.InventoryCaps Formal.PredictWin Formal.LoadoutProjection Formal.EquipmentScoring
#print axioms pathFrom_valid
#print axioms pathFrom_len_eq_cheb
#print axioms kingWalk_len_ge_cheb
#print axioms pathFrom_cost
#print axioms cheb_le_manhattan
#print axioms estimatedTime_eq_cheb
#print axioms batch_ge_one
#print axioms batch_le_remaining
#print axioms batch_le_cap
#print axioms batch_fits
#print axioms non_task_one
#print axioms cap_eq_max_of_four
#print axioms cap_eq_max_one_of_four
#print axioms equipped_ge_one
#print axioms recipe_cap_ge_safety
#print axioms overstock_exact
#print axioms overstock_pos_of_over
#print axioms overstock_zero_of_not_over
#print axioms predict_win_eq_sim
#print axioms maxturns_sound
#print axioms predict_win_mono_player
#print axioms predict_win_mono_monsterhp
#print axioms proj_identity
#print axioms proj_additive
#print axioms guarded_eq_unconditional
#print axioms dropZeros_preserves_nonzero
#print axioms dropZeros_zero_reads_zero
#print axioms pickslot_score_optimal
#print axioms pickslot_no_downgrade
#print axioms pickslot_best_feasible
#print axioms pickslot_ties_keep_current
#print axioms pickslot_empty_fills
#print axioms pickslot_no_candidates_keeps
#print axioms weapon_score_nonneg
