import Formal
open Formal.CalculatePath Formal.TaskBatch Formal.InventoryCaps Formal.PredictWin Formal.LoadoutProjection Formal.EquipmentScoring Formal.SkillXpCurve Formal.RecipeClosure
#print axioms pathFrom_valid
#print axioms pathFrom_len_eq_cheb
#print axioms kingWalk_len_ge_cheb
#print axioms pathFrom_cost
#print axioms cheb_le_manhattan
#print axioms estimatedTime_eq_cheb
#print axioms batch_ge_one
#print axioms batch_le_remaining
#print axioms batch_le_cap
#print axioms batch_fits
#print axioms non_task_one
#print axioms cap_eq_max_of_four
#print axioms cap_eq_max_one_of_four
#print axioms equipped_ge_one
#print axioms recipe_cap_ge_safety
#print axioms overstock_exact
#print axioms overstock_pos_of_over
#print axioms overstock_zero_of_not_over
#print axioms predict_win_eq_sim
#print axioms maxturns_sound
#print axioms predict_win_mono_player
#print axioms predict_win_mono_monsterhp
#print axioms proj_identity
#print axioms proj_additive
#print axioms guarded_eq_unconditional
#print axioms dropZeros_preserves_nonzero
#print axioms dropZeros_zero_reads_zero
#print axioms pickslot_score_optimal
#print axioms pickslot_no_downgrade
#print axioms pickslot_best_feasible
#print axioms pickslot_ties_keep_current
#print axioms pickslot_empty_fills
#print axioms pickslot_no_candidates_keeps
#print axioms weapon_score_nonneg
#print axioms required_xp_observed
#print axioms required_xp_zero
#print axioms confNum_le_confDen
#print axioms is_confident_iff_full
#print axioms cycles_zero
#print axioms cycles_inf
#print axioms total_monotone
#print axioms growth_default_iff
#print axioms growth_nondefault_of_pair
#print axioms reachable_iff_satN
#print axioms reachable_least
#print axioms closureItems_sound
#print axioms closureItems_complete
#print axioms craftableList_isCraftable
#print axioms neededList_isNeeded
#print axioms rawUnits_eq_cost
#print axioms rawUnits_revisit
#print axioms remaining_decreasing
#print axioms rawUnits_fuel_stable
#print axioms Formal.TaskFeasibility.worst_eq_max_unmet
#print axioms Formal.TaskFeasibility.worst_is_max
#print axioms Formal.TaskFeasibility.none_iff_no_unmet
#print axioms Formal.TaskFeasibility.worst_is_real_gap
#print axioms Formal.TaskFeasibility.monster_gate
#print axioms Formal.TaskFeasibility.monster_gate_boundary_false
#print axioms Formal.TaskFeasibility.monster_gate_just_past
#print axioms Formal.TaskFeasibility.monster_gate_zero_never
#print axioms Formal.PrerequisiteGraph.prereqs_recipe_with_skill
#print axioms Formal.PrerequisiteGraph.prereqs_recipe_no_skill
#print axioms Formal.PrerequisiteGraph.prereqs_membership
#print axioms Formal.PrerequisiteGraph.prereqs_resource
#print axioms Formal.PrerequisiteGraph.prereqs_leaf
#print axioms Formal.PrerequisiteGraph.resource_branch_no_item
#print axioms Formal.PrerequisiteGraph.firstResSkill_sound
#print axioms Formal.PrerequisiteGraph.combat_capable_iff
#print axioms Formal.PrerequisiteGraph.combat_capable_demorgan
#print axioms Formal.PrerequisiteGraph.combat_capable_empty
#print axioms Formal.Objective.is_attainable_eq_grounding
#print axioms Formal.Objective.groundedByN_sound
#print axioms Formal.Objective.grounded_groundedByN
#print axioms Formal.Objective.attainAux_sound
#print axioms Formal.Objective.best_gear_argmax
#print axioms Formal.Objective.bestGear_optimal
#print axioms Formal.Objective.gapSum_nonneg
#print axioms Formal.Objective.gapSum_le_targetSum
#print axioms Formal.Objective.charGap_bounds
#print axioms Formal.Objective.is_complete_iff
#print axioms Formal.Objective.axisGap_zero_iff
#print axioms Formal.PrerequisiteGraph.combat_capable_witness
#print axioms Formal.StrategyTraversal.is_reachable_eq_grounding
#print axioms Formal.StrategyTraversal.groundedByN_sound
#print axioms Formal.StrategyTraversal.grounded_groundedByN
#print axioms Formal.StrategyTraversal.reachAux_sound
#print axioms Formal.StrategyTraversal.unmetClosureSize_ge_one
#print axioms Formal.StrategyTraversal.unmetClosureSize_eq_count
#print axioms Formal.StrategyTraversal.unmetNodes_unmet
#print axioms Formal.StrategyTraversal.actionable_step_sound
#print axioms Formal.StrategyTraversal.actionable_step_none_iff
#print axioms Formal.StrategyTraversal.actionable_step_reach
#print axioms Formal.StrategyTraversal.rootCost_ge_one
#print axioms Formal.StrategyTraversal.reachable_implies_actionable
#print axioms Formal.StrategyTraversal.grounded_unmet_has_actionable
#print axioms Formal.BankSelection.deposits_exact
#print axioms Formal.BankSelection.deposits_mem_iff
#print axioms Formal.BankSelection.freeze_invariant
#print axioms Formal.BankSelection.task_inputs_protected
#print axioms Formal.BankSelection.task_material_not_deposited
#print axioms Formal.BankSelection.keep_closed
#print axioms Formal.BankSelection.recipeMaterials_closed
#print axioms Formal.BankSelection.recipeMaterialList_complete
#print axioms Formal.BankSelection.best_weapon_argmax
#print axioms Formal.BankSelection.best_weapon_is_fighting
#print axioms Formal.StuckDetector.recent_since_window
#print axioms Formal.StuckDetector.recentSince_mem_global
#print axioms Formal.StuckDetector.detect_precedence
#print axioms Formal.StuckDetector.detect_frozen_wins
#print axioms Formal.StuckDetector.detect_osc_over_noprog
#print axioms Formal.StuckDetector.noprog_threshold
#print axioms Formal.StuckDetector.osc_threshold
#print axioms Formal.StuckDetector.frozen_threshold
#print axioms Formal.StuckDetector.ack_suppression_noprog
#print axioms Formal.StuckDetector.ack_suppression_frozen
#print axioms Formal.StuckDetector.ack_suppression_osc
#print axioms Formal.StuckDetector.ack_noprog_cannot_fire
#print axioms Formal.StuckDetector.ack_frozen_cannot_fire
#print axioms Formal.StuckDetector.ack_osc_cannot_fire
#print axioms Formal.PriorityBand.clamp_lower_bound
#print axioms Formal.PriorityBand.clamp_upper_bound
#print axioms Formal.PriorityBand.clamp_below_survival
#print axioms Formal.OwnedCount.ownedCount_eq_total
#print axioms Formal.OwnedCount.ownedCount_counts_equipped
#print axioms Formal.OwnedCount.ownedCount_monotone
#print axioms Formal.UpgradeSelection.best_by_value_not_worse
#print axioms Formal.UpgradeSelection.best_by_value_tie_inv
#print axioms Formal.UpgradeSelection.craftableCmp_trichotomy
#print axioms Formal.UpgradeSelection.craftableCmp_swap
#print axioms Formal.UpgradeSelection.craftableCmp_lt_trans
#print axioms Formal.UpgradeSelection.craftableCmp_eq_imp_code
#print axioms Formal.UpgradeSelection.inventoryCmp_trichotomy
#print axioms Formal.UpgradeSelection.inventoryCmp_swap
#print axioms Formal.UpgradeSelection.inventoryCmp_lt_trans
#print axioms Formal.UpgradeSelection.inventoryCmp_eq_imp_code
#print axioms Formal.UpgradeSelection.bestByKey_sound
#print axioms Formal.Scalarizer.scalarYield_eq_components
#print axioms Formal.Scalarizer.scalarYield_mono_charxp
#print axioms Formal.Scalarizer.scalarYield_mono_gold
#print axioms Formal.Scalarizer.scalarYield_mono_coins
#print axioms Formal.Scalarizer.skillSum_mono_one
#print axioms Formal.Scalarizer.relevant_weight_dominates
#print axioms Formal.Scalarizer.coinsSpent_inverts
#print axioms Formal.PlannerAdmissibility.fScore_eq_g_at_goal_of_admissible
#print axioms Formal.PlannerAdmissibility.firstSatisfied_least_cost_of_admissible
#print axioms Formal.PlannerAdmissibility.zero_h_admissible
#print axioms Formal.PlannerAdmissibility.RHP_h_admissible
#print axioms Formal.PlannerAdmissibility.RHP_optimal_popped_before_rest
#print axioms Formal.PlannerAdmissibility.RHP_first_satisfied_is_optimal
#print axioms Formal.PlannerAdmissibility.RHP_optimal_strictly_cheaper_than_rest
#print axioms Formal.ArbiterSelect.select_pure_guard_wins
#print axioms Formal.ArbiterSelect.select_pure_sticky_idempotent
#print axioms Formal.ArbiterSelect.select_pure_no_commitment_is_walk
#print axioms Formal.ArbiterSelect.walk_returns_head
#print axioms Formal.ArbiterSelect.guardPrecedes_of_head_guard
#print axioms Formal.ArbiterSelect.findCommitted_some_props
#print axioms Formal.TaskDecision.combat_or_no_history_pivots
#print axioms Formal.TaskDecision.req_none_pursues
#print axioms Formal.TaskDecision.no_div_by_zero_from_invariant
#print axioms Formal.TaskDecision.requiredVpc_antitone_in_confidence
#print axioms Formal.TaskDecision.decision_pursue_confidence_monotone
#print axioms Formal.TaskDecision.decision_pursue_vpc_monotone
open Formal.WeightedRemaining in
#print axioms complete_imp_zero
open Formal.WeightedRemaining in
#print axioms zero_iff_complete_pos
open Formal.WeightedRemaining in
#print axioms bug_teeth_witness
open Formal.WeightedRemaining in
#print axioms mono_head
open Formal.WeightedRemaining in
#print axioms nonneg
#print axioms Formal.LowYieldCancel.no_task_never_fires
#print axioms Formal.LowYieldCancel.no_samples_blocks
#print axioms Formal.LowYieldCancel.fires_monotone_in_alt
#print axioms Formal.LowYieldCancel.zero_fast_path_fires_unconditionally
#print axioms Formal.LowYieldCancel.zero_fast_path_fires_with_low_confidence_witness
#print axioms Formal.LowYieldCancel.positive_current_fires_implies_margin
#print axioms Formal.LowYieldCancel.positive_current_fires_implies_confidence
#print axioms Formal.StrategyBlend.balancingScaled_ge_min
#print axioms Formal.StrategyBlend.balancingScaled_le_max
#print axioms Formal.StrategyBlend.balancingScaled_at_threshold
#print axioms Formal.StrategyBlend.balancingScaled_at_equal_clamps_to_min
#print axioms Formal.StrategyBlend.balancingScaled_mono
#print axioms Formal.StrategyBlend.learnedBlend_w_zero
#print axioms Formal.StrategyBlend.learnedBlend_w_one
#print axioms Formal.StrategyBlend.learnedBlend_ge_value_when_le
#print axioms Formal.StrategyBlend.learnedBlend_le_normalized_when_le
#print axioms Formal.StrategyBlend.learnedBlend_ge_normalized_when_ge
#print axioms Formal.StrategyBlend.learnedBlend_le_value_when_ge
#print axioms Formal.StrategyBlend.learnedBlend_mono_normalized
#print axioms Formal.StrategyBlend.learnedBlend_mono_value
#print axioms Formal.DecideKey.decideCmp_trichotomy
#print axioms Formal.DecideKey.decideCmp_swap
#print axioms Formal.DecideKey.decideCmp_lt_trans
#print axioms Formal.DecideKey.decideCmp_eq_imp_repr
#print axioms Formal.DecideKey.decideCmp_eq_imp_negFinal
#print axioms Formal.DecideKey.decideCmp_eq_imp_effort
#print axioms Formal.DecideKey.goalReprOfGuard_nonempty
#print axioms Formal.DecideKey.goalReprOfMeans_nonempty
#print axioms Formal.CyclesForProgress.cyclesForProgressPure_eq_median_concat
#print axioms Formal.CyclesForProgress.warmup_blocks
#print axioms Formal.CyclesForProgress.empty_none
#print axioms Formal.CyclesForProgress.satisfyIntervals_pos
#print axioms Formal.CyclesForProgress.strictIntervals_pos
#print axioms Formal.CyclesForProgress.allIntervals_pos
#print axioms Formal.GatherApply.is_applicable_imp_free_ge
#print axioms Formal.GatherApply.apply_inventory_safe
#print axioms Formal.GatherApply.apply_inventory_safe_prod
#print axioms Formal.GatherApply.applyN_used
#print axioms Formal.GatherApply.applyN_cap
#print axioms Formal.GatherApply.chain_safe
#print axioms Formal.GatherApply.chain_safe_min_free_witness
#print axioms Formal.GatherApply.is_applicable_boundary_witness
#print axioms Formal.GatherApply.is_applicable_off_boundary_witness
#print axioms Formal.NpcBuyInventory.npc_buy_is_applicable_imp_free_ge
#print axioms Formal.NpcBuyInventory.npc_buy_is_applicable_imp_gold_ge
#print axioms Formal.NpcBuyInventory.npc_buy_apply_inventory_safe
#print axioms Formal.NpcBuyInventory.applyN_used
#print axioms Formal.NpcBuyInventory.applyN_cap
#print axioms Formal.NpcBuyInventory.npc_buy_chain_safe
#print axioms Formal.NpcBuyInventory.boundary_quantity_eq_free_witness
#print axioms Formal.NpcBuyInventory.regression_used9_cap10_qty5_refused
#print axioms Formal.NpcBuyInventory.chain_safe_boundary_witness
#print axioms Formal.NpcBuyInventory.gold_short_refused_witness
#print axioms Formal.NpcBuyInventory.gold_exact_min_accepted_witness
#print axioms Formal.ActionCostNonneg.constantCost_nonneg
#print axioms Formal.ActionCostNonneg.distanceCost_nonneg
#print axioms Formal.ActionCostNonneg.qtyCost_nonneg
#print axioms Formal.ActionCostNonneg.qtyCost_ge_per_unit
#print axioms Formal.ActionCostNonneg.ratMax_ge_right
#print axioms Formal.ActionCostNonneg.ratMax_pos_of_right_pos
#print axioms Formal.ActionCostNonneg.learnedFraction_nonneg
#print axioms Formal.ActionCostNonneg.learnedCost_nonneg
#print axioms Formal.ActionCostNonneg.rateFloorProd_pos
#print axioms Formal.ActionCostNonneg.fight_cost_nonneg
#print axioms Formal.ActionCostNonneg.gather_cost_nonneg
#print axioms Formal.ActionCostNonneg.move_cost_nonneg
#print axioms Formal.ActionCostNonneg.delete_cost_nonneg
#print axioms Formal.ActionCostNonneg.all_actions_cost_nonneg
#print axioms Formal.RealizableLoadout.isRealizable_iff_demand_le_ownership
#print axioms Formal.RealizableLoadout.apply_cur_ge_1
#print axioms Formal.RealizableLoadout.ownership_counts_equipped
#print axioms Formal.RealizableLoadout.regression_ring_pair_realizable
#print axioms Formal.RealizableLoadout.regression_buggy_output_not_realizable
#print axioms Formal.RealizableLoadout.empty_loadout_realizable
#print axioms Formal.RealizableLoadout.isRealizable_mono_inv
#print axioms Formal.ApplyBaseline.moveApply_preserves_baseline
#print axioms Formal.ApplyBaseline.equipApply_preserves_baseline
#print axioms Formal.ApplyBaseline.claimApply_preserves_baseline
#print axioms Formal.ApplyBaseline.headline_preserves_baseline
#print axioms Formal.ApplyBaseline.preservesBaseline_refl
#print axioms Formal.ApplyBaseline.preservesBaseline_trans
-- InventoryChainSafe (REAL BUGS #7-#11): four chain_safe instantiations + TaskCancel coin
#print axioms Formal.InventoryChainSafe.isApplicableK_imp_free_ge
#print axioms Formal.InventoryChainSafe.applyK_inventory_safe
#print axioms Formal.InventoryChainSafe.applyKN_used
#print axioms Formal.InventoryChainSafe.applyKN_cap
#print axioms Formal.InventoryChainSafe.chain_safe_template
#print axioms Formal.InventoryChainSafe.withdraw_is_applicable_imp_free_ge
#print axioms Formal.InventoryChainSafe.withdraw_is_applicable_imp_bank_ge
#print axioms Formal.InventoryChainSafe.withdraw_apply_inventory_safe
#print axioms Formal.InventoryChainSafe.withdraw_chain_safe
#print axioms Formal.InventoryChainSafe.withdraw_boundary_quantity_eq_free_witness
#print axioms Formal.InventoryChainSafe.withdraw_regression_used9_cap10_qty5_refused
#print axioms Formal.InventoryChainSafe.claim_is_applicable_imp_free_ge
#print axioms Formal.InventoryChainSafe.claim_apply_inventory_safe
#print axioms Formal.InventoryChainSafe.claim_chain_safe
#print axioms Formal.InventoryChainSafe.claim_boundary_witness
#print axioms Formal.InventoryChainSafe.claim_regression_full_bag_refused
#print axioms Formal.InventoryChainSafe.claim_no_pending_refused
#print axioms Formal.InventoryChainSafe.unequip_is_applicable_imp_free_ge
#print axioms Formal.InventoryChainSafe.unequip_apply_inventory_safe
#print axioms Formal.InventoryChainSafe.unequip_chain_safe
#print axioms Formal.InventoryChainSafe.unequip_boundary_witness
#print axioms Formal.InventoryChainSafe.unequip_regression_full_bag_refused
#print axioms Formal.InventoryChainSafe.unequip_empty_slot_refused
#print axioms Formal.InventoryChainSafe.task_exchange_is_applicable_imp_free_ge
#print axioms Formal.InventoryChainSafe.task_exchange_is_applicable_imp_coins_ge
#print axioms Formal.InventoryChainSafe.task_exchange_apply_inventory_safe
#print axioms Formal.InventoryChainSafe.task_exchange_chain_safe
#print axioms Formal.InventoryChainSafe.task_exchange_boundary_witness
#print axioms Formal.InventoryChainSafe.task_exchange_regression_full_bag_refused
#print axioms Formal.InventoryChainSafe.task_exchange_coin_short_refused
#print axioms Formal.InventoryChainSafe.task_cancel_is_applicable_imp_coin_ge
#print axioms Formal.InventoryChainSafe.task_cancel_apply_coin_eq_pre_minus_one
#print axioms Formal.InventoryChainSafe.task_cancel_apply_strictly_decreases
#print axioms Formal.InventoryChainSafe.task_cancel_applyN_coin
#print axioms Formal.InventoryChainSafe.task_cancel_chain_coin_safe
#print axioms Formal.InventoryChainSafe.task_cancel_boundary_witness
#print axioms Formal.InventoryChainSafe.task_cancel_no_coin_refused
#print axioms Formal.InventoryChainSafe.task_cancel_no_task_refused
#print axioms Formal.Phase7Invariants.baseValue_nonpos_zero
#print axioms Formal.Phase7Invariants.baseValue_pos_ge_one
#print axioms Formal.Phase7Invariants.baseValue_nonneg
#print axioms Formal.Phase7Invariants.baseValue_total_needed_zero_returns_zero
#print axioms Formal.Phase7Invariants.isApplicable_imp_slot_in_table
#print axioms Formal.Phase7Invariants.isApplicable_imp_inv_pos
#print axioms Formal.Phase7Invariants.isApplicable_imp_level_ge
#print axioms Formal.Phase7Invariants.isApplicable_slot_mismatch_refused
#print axioms Formal.Phase7Invariants.isApplicable_no_stats_refused
#print axioms Formal.Phase7Invariants.isApplicable_boundary_witness
#print axioms Formal.Phase7Invariants.isApplicable_ring_into_helmet_refused
#print axioms Formal.Phase7Invariants.inventoryUsed_eq_sum
#print axioms Formal.Phase7Invariants.inventoryFree_eq_diff
#print axioms Formal.Phase7Invariants.inventoryFree_plus_used_eq_max
#print axioms Formal.Phase7Invariants.hpPercent_maxhp_zero
#print axioms Formal.Phase7Invariants.hpPercent_maxhp_pos
#print axioms Formal.Phase7Invariants.hpPercent_nonneg
#print axioms Formal.StoreWarmup.warmupGatedMedian_below_gate
#print axioms Formal.StoreWarmup.warmupGatedMedian_at_or_above_gate
#print axioms Formal.StoreWarmup.warmupGatedSuccessRate_below_gate
#print axioms Formal.StoreWarmup.warmupGatedSuccessRate_at_or_above_gate
#print axioms Formal.StoreWarmup.warmupGatedSuccessRate_nonneg
-- Phase 8 — mixed batch
#print axioms Formal.Phase8Invariants.recycle_is_applicable_imp_skill_ge
#print axioms Formal.Phase8Invariants.recycle_is_applicable_imp_free_ge_net
#print axioms Formal.Phase8Invariants.recycle_apply_inventory_safe
#print axioms Formal.Phase8Invariants.recycle_apply_inventory_safe_zero_net
#print axioms Formal.Phase8Invariants.recycle_chain_safe
#print axioms Formal.Phase8Invariants.recycle_boundary_witness
#print axioms Formal.Phase8Invariants.recycle_regression_full_bag_net2_refused
#print axioms Formal.Phase8Invariants.recycle_regression_skill_low_refused
#print axioms Formal.Phase8Invariants.recycle_no_crafting_skill_refused
#print axioms Formal.Phase8Invariants.recycle_no_workshop_refused
#print axioms Formal.Phase8Invariants.buyBankExpansion_preserves_bankItems
#print axioms Formal.Phase8Invariants.buyBankExpansion_preserves_capacity
#print axioms Formal.Phase8Invariants.bank_expansion_projection_gap
#print axioms Formal.Phase8Invariants.bank_expansion_gap_witness
#print axioms Formal.Phase8Invariants.accept_preserves_consistent
#print axioms Formal.Phase8Invariants.complete_preserves_consistent
#print axioms Formal.Phase8Invariants.cancel_preserves_consistent
#print axioms Formal.Phase8Invariants.accept_not_reapplicable
#print axioms Formal.Phase8Invariants.accept_applicable_after_complete
#print axioms Formal.Phase8Invariants.accept_applicable_after_cancel
#print axioms Formal.Phase8Invariants.accept_real_task_refused
#print axioms Formal.Phase8Invariants.accept_pending_refused
#print axioms Formal.Phase8Invariants.claim_value_pos_iff_pending
#print axioms Formal.Phase8Invariants.claim_value_pos_with_full_bag_witness
