import Formal
open Formal.CalculatePath Formal.TaskBatch Formal.InventoryCaps Formal.PredictWin Formal.LoadoutProjection Formal.EquipmentScoring Formal.SkillXpCurve Formal.RecipeClosure
#print axioms pathFrom_valid
#print axioms pathFrom_len_eq_cheb
#print axioms kingWalk_len_ge_cheb
#print axioms pathFrom_cost
#print axioms cheb_le_manhattan
#print axioms estimatedTime_eq_cheb
#print axioms batch_ge_one
#print axioms batch_le_remaining
#print axioms batch_le_cap
#print axioms batch_fits
#print axioms non_task_one
#print axioms cap_eq_max_of_four
#print axioms cap_eq_max_one_of_four
#print axioms equipped_ge_one
#print axioms recipe_cap_ge_safety
#print axioms overstock_exact
#print axioms overstock_pos_of_over
#print axioms overstock_zero_of_not_over
#print axioms predict_win_eq_sim
#print axioms maxturns_sound
#print axioms predict_win_mono_player
#print axioms predict_win_mono_monsterhp
#print axioms proj_identity
#print axioms proj_additive
#print axioms guarded_eq_unconditional
#print axioms dropZeros_preserves_nonzero
#print axioms dropZeros_zero_reads_zero
#print axioms pickslot_score_optimal
#print axioms pickslot_no_downgrade
#print axioms pickslot_best_feasible
#print axioms pickslot_ties_keep_current
#print axioms pickslot_empty_fills
#print axioms pickslot_no_candidates_keeps
#print axioms weapon_score_nonneg
#print axioms required_xp_observed
#print axioms required_xp_zero
#print axioms confNum_le_confDen
#print axioms is_confident_iff_full
#print axioms cycles_zero
#print axioms cycles_inf
#print axioms total_monotone
#print axioms growth_default_iff
#print axioms growth_nondefault_of_pair
#print axioms reachable_iff_satN
#print axioms reachable_least
#print axioms closureItems_sound
#print axioms closureItems_complete
#print axioms craftableList_isCraftable
#print axioms neededList_isNeeded
#print axioms rawUnits_eq_cost
#print axioms rawUnits_revisit
#print axioms remaining_decreasing
#print axioms rawUnits_fuel_stable
#print axioms Formal.TaskFeasibility.worst_eq_max_unmet
#print axioms Formal.TaskFeasibility.worst_is_max
#print axioms Formal.TaskFeasibility.none_iff_no_unmet
#print axioms Formal.TaskFeasibility.worst_is_real_gap
#print axioms Formal.TaskFeasibility.monster_gate
#print axioms Formal.TaskFeasibility.monster_gate_boundary_false
#print axioms Formal.TaskFeasibility.monster_gate_just_past
#print axioms Formal.TaskFeasibility.monster_gate_zero_never
