"""The grind-cycle census (Phase 2d-L3 of docs/PLAN_decision_architecture_redesign.md).

`Formal.Liveness.GrindCycles.grind_cycles_reach_target` proves a grind reaches
its target when each CYCLE is a run of preparatory legs followed by the leg that
earns the skill's XP. This census binds that shape to production: for every
scenario and skill of the open-rung grid, it decomposes one grind cycle
(`decompose(ReachSkillGoal(skill, level + 1))`, the arbiter's own call) and
classifies the plan by its LAST leg:

  * EARNS: a craft of an item of the skill, or a gather of a resource of it;
  * EARNS_SUBSKILL: a craft or gather of ANOTHER skill — the plan met a skill
    gate and ends in that sub-grind's own earning leg;
  * DECLINED: decomposition declined (the A* fallback serves it; counted);
  * NO_EARNING_LEG: the plan ends in a leg that earns no skill — the cycle the
    proof assumes does not exist. Must be zero (`--check` gates on it).
"""

from dataclasses import dataclass
from enum import Enum

from artifactsmmo_cli.ai.actions.base import Action
from artifactsmmo_cli.ai.actions.crafting import CraftAction
from artifactsmmo_cli.ai.actions.factory import build_actions
from artifactsmmo_cli.ai.actions.gathering import GatherAction
from artifactsmmo_cli.ai.craft_plan_gen import decompose
from artifactsmmo_cli.ai.game_data import GameData
from artifactsmmo_cli.ai.goals.reach_skill import ReachSkillGoal
from artifactsmmo_cli.ai.scenario import SCENARIOS
from artifactsmmo_cli.ai.selection_context import SelectionContext
from artifactsmmo_cli.ai.tiers.objective import CharacterObjective
from artifactsmmo_cli.ai.world_state import SKILL_NAMES
from artifactsmmo_cli.audit.open_rung_completeness import census_state


class GrindCycleGap(Enum):
    EARNS = "earns"
    EARNS_SUBSKILL = "earns_subskill"
    DECLINED = "declined"
    NO_EARNING_LEG = "no_earning_leg"


@dataclass(frozen=True)
class GrindCycleResult:
    scenario: str
    skill: str
    level: int
    plan: tuple[str, ...]
    gap: GrindCycleGap


def earned_skill(action: Action, game_data: GameData) -> str | None:
    """The skill whose XP `action` earns: a craft's crafting skill, a gather's
    gathering skill; None for any other leg."""
    if isinstance(action, CraftAction):
        stats = game_data.item_stats(action.code)
        return stats.crafting_skill if stats is not None and stats.crafting_skill else None
    if isinstance(action, GatherAction):
        gate = game_data.resource_skill_level(action.resource_code)
        return gate[0] if gate is not None else None
    return None


def classify(skill: str, plan: list[Action] | None, game_data: GameData) -> GrindCycleGap:
    if plan is None:
        return GrindCycleGap.DECLINED
    earned = earned_skill(plan[-1], game_data)
    if earned == skill:
        return GrindCycleGap.EARNS
    if earned is not None:
        return GrindCycleGap.EARNS_SUBSKILL
    return GrindCycleGap.NO_EARNING_LEG


_CTX = SelectionContext(bank_accessible=True, bank_required_level=0, bank_unlock_monster=None,
                        initial_xp=0, task_exchange_min_coins=0, combat_monster=None)


def run_census(game_data: GameData) -> list[GrindCycleResult]:
    """Every `(scenario, skill)` cell of the open-rung grid, in its order."""
    objective = CharacterObjective.from_game_data(game_data)
    results: list[GrindCycleResult] = []
    for name, scenario in SCENARIOS.items():
        state = census_state(scenario, game_data)
        actions = build_actions(game_data, state, objective, bank_accessible=True,
                                task_exchange_min_coins=0)
        for skill in SKILL_NAMES:
            level = state.skills[skill]
            plan = decompose(ReachSkillGoal(skill, level + 1), state, game_data, actions, _CTX)
            results.append(GrindCycleResult(name, skill, level,
                                            tuple(repr(a) for a in plan or []),
                                            classify(skill, plan, game_data)))
    return results


def summary_line(results: list[GrindCycleResult]) -> str:
    counts = {gap: sum(1 for r in results if r.gap is gap) for gap in GrindCycleGap}
    return f"{len(results)} cells; " + ", ".join(f"{gap.value} {n}" for gap, n in counts.items())


def render_matrix(results: list[GrindCycleResult]) -> str:
    lines = ["# Grind-cycle census", "",
             "> Generated by `scripts/gen_grind_cycle.py` from the committed bundle. "
             "See `audit/grind_cycle_census.py` for the classes.", "",
             summary_line(results), "",
             "| Scenario | Skill | Level | Class | Plan |", "|---|---|---|---|---|"]
    lines += [f"| {r.scenario} | {r.skill} | {r.level} | {r.gap.value} | {' → '.join(r.plan)} |"
              for r in results]
    return "\n".join(lines) + "\n"
